# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1013, 820)
        MainWindow.setMinimumSize(QtCore.QSize(1013, 820))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.searchContent = QtWidgets.QLineEdit(self.centralwidget)
        self.searchContent.setClearButtonEnabled(True)
        self.searchContent.setObjectName("searchContent")
        self.gridLayout_3.addWidget(self.searchContent, 0, 0, 1, 1)
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchButton.sizePolicy().hasHeightForWidth())
        self.searchButton.setSizePolicy(sizePolicy)
        self.searchButton.setObjectName("searchButton")
        self.gridLayout_3.addWidget(self.searchButton, 0, 1, 1, 1)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveButton.sizePolicy().hasHeightForWidth())
        self.saveButton.setSizePolicy(sizePolicy)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout_3.addWidget(self.saveButton, 0, 2, 1, 1)
        self.createBotton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createBotton.sizePolicy().hasHeightForWidth())
        self.createBotton.setSizePolicy(sizePolicy)
        self.createBotton.setObjectName("createBotton")
        self.gridLayout_3.addWidget(self.createBotton, 0, 3, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelButton.sizePolicy().hasHeightForWidth())
        self.cancelButton.setSizePolicy(sizePolicy)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout_3.addWidget(self.cancelButton, 0, 4, 1, 1)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_2.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget_2.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_2.setTabBarAutoHide(True)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.tabWidget = QtWidgets.QTabWidget(self.tab)
        self.tabWidget.setObjectName("tabWidget")
        self.companyTab = QtWidgets.QWidget()
        self.companyTab.setObjectName("companyTab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.companyTab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_3 = QtWidgets.QGroupBox(self.companyTab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.depStructLable = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depStructLable.sizePolicy().hasHeightForWidth())
        self.depStructLable.setSizePolicy(sizePolicy)
        self.depStructLable.setObjectName("depStructLable")
        self.gridLayout_10.addWidget(self.depStructLable, 0, 0, 1, 1)
        self.previewPic = QtWidgets.QListWidget(self.groupBox_3)
        self.previewPic.setObjectName("previewPic")
        self.gridLayout_10.addWidget(self.previewPic, 1, 0, 2, 1)
        self.previewButton = QtWidgets.QPushButton(self.groupBox_3)
        self.previewButton.setObjectName("previewButton")
        self.gridLayout_10.addWidget(self.previewButton, 2, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.borderLable = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.borderLable.sizePolicy().hasHeightForWidth())
        self.borderLable.setSizePolicy(sizePolicy)
        self.borderLable.setObjectName("borderLable")
        self.gridLayout_9.addWidget(self.borderLable, 0, 1, 1, 1)
        self.fontLable = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontLable.sizePolicy().hasHeightForWidth())
        self.fontLable.setSizePolicy(sizePolicy)
        self.fontLable.setObjectName("fontLable")
        self.gridLayout_9.addWidget(self.fontLable, 0, 2, 1, 1)
        self.level1Lable = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.level1Lable.sizePolicy().hasHeightForWidth())
        self.level1Lable.setSizePolicy(sizePolicy)
        self.level1Lable.setObjectName("level1Lable")
        self.gridLayout_9.addWidget(self.level1Lable, 1, 0, 1, 1)
        self.level1Border = QtWidgets.QPushButton(self.groupBox_2)
        self.level1Border.setMinimumSize(QtCore.QSize(20, 20))
        self.level1Border.setMaximumSize(QtCore.QSize(20, 20))
        self.level1Border.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.level1Border.setAutoFillBackground(False)
        self.level1Border.setStyleSheet("background-color:rgb(0, 128, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"gridline-color:rgb(0, 0, 0);")
        self.level1Border.setText("")
        self.level1Border.setObjectName("level1Border")
        self.gridLayout_9.addWidget(self.level1Border, 1, 1, 1, 1)
        self.level1Font = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.level1Font.sizePolicy().hasHeightForWidth())
        self.level1Font.setSizePolicy(sizePolicy)
        self.level1Font.setMinimumSize(QtCore.QSize(20, 20))
        self.level1Font.setMaximumSize(QtCore.QSize(20, 20))
        self.level1Font.setStyleSheet("background-color:rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"gridline-color:rgb(0, 0, 0);")
        self.level1Font.setText("")
        self.level1Font.setObjectName("level1Font")
        self.gridLayout_9.addWidget(self.level1Font, 1, 2, 1, 1)
        self.level1Width = QtWidgets.QSpinBox(self.groupBox_2)
        self.level1Width.setMinimumSize(QtCore.QSize(42, 20))
        self.level1Width.setMaximumSize(QtCore.QSize(42, 20))
        self.level1Width.setMinimum(1)
        self.level1Width.setProperty("value", 3)
        self.level1Width.setObjectName("level1Width")
        self.gridLayout_9.addWidget(self.level1Width, 1, 3, 1, 1)
        self.level2Lable = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.level2Lable.sizePolicy().hasHeightForWidth())
        self.level2Lable.setSizePolicy(sizePolicy)
        self.level2Lable.setObjectName("level2Lable")
        self.gridLayout_9.addWidget(self.level2Lable, 2, 0, 1, 1)
        self.level2Border = QtWidgets.QPushButton(self.groupBox_2)
        self.level2Border.setMinimumSize(QtCore.QSize(20, 20))
        self.level2Border.setMaximumSize(QtCore.QSize(20, 20))
        self.level2Border.setStyleSheet("background-color:rgb(128,0, 0);\n"
"border-color: rgb(0,0, 0);\n"
"gridline-color:rgb(0, 0, 0);")
        self.level2Border.setText("")
        self.level2Border.setObjectName("level2Border")
        self.gridLayout_9.addWidget(self.level2Border, 2, 1, 1, 1)
        self.level2Font = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.level2Font.sizePolicy().hasHeightForWidth())
        self.level2Font.setSizePolicy(sizePolicy)
        self.level2Font.setMinimumSize(QtCore.QSize(20, 20))
        self.level2Font.setMaximumSize(QtCore.QSize(20, 20))
        self.level2Font.setStyleSheet("background-color:rgb(0,0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"gridline-color:rgb(0, 0, 0);")
        self.level2Font.setText("")
        self.level2Font.setObjectName("level2Font")
        self.gridLayout_9.addWidget(self.level2Font, 2, 2, 1, 1)
        self.level2Width = QtWidgets.QSpinBox(self.groupBox_2)
        self.level2Width.setMinimumSize(QtCore.QSize(42, 20))
        self.level2Width.setMaximumSize(QtCore.QSize(42, 20))
        self.level2Width.setMinimum(1)
        self.level2Width.setProperty("value", 3)
        self.level2Width.setObjectName("level2Width")
        self.gridLayout_9.addWidget(self.level2Width, 2, 3, 1, 1)
        self.level3Lable = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.level3Lable.sizePolicy().hasHeightForWidth())
        self.level3Lable.setSizePolicy(sizePolicy)
        self.level3Lable.setObjectName("level3Lable")
        self.gridLayout_9.addWidget(self.level3Lable, 3, 0, 1, 1)
        self.level3Border = QtWidgets.QPushButton(self.groupBox_2)
        self.level3Border.setMinimumSize(QtCore.QSize(20, 20))
        self.level3Border.setMaximumSize(QtCore.QSize(20, 20))
        self.level3Border.setStyleSheet("background-color:rgb(0, 0, 128);\n"
"border-color: rgb(0, 0, 0);\n"
"gridline-color:rgb(0, 0, 0);")
        self.level3Border.setText("")
        self.level3Border.setObjectName("level3Border")
        self.gridLayout_9.addWidget(self.level3Border, 3, 1, 1, 1)
        self.level3Font = QtWidgets.QPushButton(self.groupBox_2)
        self.level3Font.setMinimumSize(QtCore.QSize(20, 20))
        self.level3Font.setMaximumSize(QtCore.QSize(20, 20))
        self.level3Font.setStyleSheet("background-color:rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"gridline-color:rgb(0, 0, 0);")
        self.level3Font.setText("")
        self.level3Font.setObjectName("level3Font")
        self.gridLayout_9.addWidget(self.level3Font, 3, 2, 1, 1)
        self.level3Width = QtWidgets.QSpinBox(self.groupBox_2)
        self.level3Width.setMinimumSize(QtCore.QSize(42, 20))
        self.level3Width.setMaximumSize(QtCore.QSize(42, 20))
        self.level3Width.setMinimum(1)
        self.level3Width.setProperty("value", 3)
        self.level3Width.setObjectName("level3Width")
        self.gridLayout_9.addWidget(self.level3Width, 3, 3, 1, 1)
        self.level4Lable = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.level4Lable.sizePolicy().hasHeightForWidth())
        self.level4Lable.setSizePolicy(sizePolicy)
        self.level4Lable.setObjectName("level4Lable")
        self.gridLayout_9.addWidget(self.level4Lable, 4, 0, 1, 1)
        self.level4Border = QtWidgets.QPushButton(self.groupBox_2)
        self.level4Border.setMinimumSize(QtCore.QSize(20, 20))
        self.level4Border.setMaximumSize(QtCore.QSize(20, 20))
        self.level4Border.setStyleSheet("background-color:rgb(255, 255, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"gridline-color:rgb(0, 0, 0);")
        self.level4Border.setText("")
        self.level4Border.setObjectName("level4Border")
        self.gridLayout_9.addWidget(self.level4Border, 4, 1, 1, 1)
        self.level4Font = QtWidgets.QPushButton(self.groupBox_2)
        self.level4Font.setMinimumSize(QtCore.QSize(20, 20))
        self.level4Font.setMaximumSize(QtCore.QSize(20, 20))
        self.level4Font.setStyleSheet("background-color:rgb(0,0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"gridline-color:rgb(0, 0, 0);")
        self.level4Font.setText("")
        self.level4Font.setObjectName("level4Font")
        self.gridLayout_9.addWidget(self.level4Font, 4, 2, 1, 1)
        self.level4Width = QtWidgets.QSpinBox(self.groupBox_2)
        self.level4Width.setMinimumSize(QtCore.QSize(42, 20))
        self.level4Width.setMaximumSize(QtCore.QSize(42, 20))
        self.level4Width.setMinimum(1)
        self.level4Width.setProperty("value", 3)
        self.level4Width.setObjectName("level4Width")
        self.gridLayout_9.addWidget(self.level4Width, 4, 3, 1, 1)
        self.heightLable = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heightLable.sizePolicy().hasHeightForWidth())
        self.heightLable.setSizePolicy(sizePolicy)
        self.heightLable.setObjectName("heightLable")
        self.gridLayout_9.addWidget(self.heightLable, 0, 3, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_2, 0, 1, 2, 1)
        self.gridLayout_7.addWidget(self.groupBox_3, 4, 2, 1, 1)
        self.fileInfo = QtWidgets.QGroupBox(self.companyTab)
        self.fileInfo.setObjectName("fileInfo")
        self.gridLayout = QtWidgets.QGridLayout(self.fileInfo)
        self.gridLayout.setObjectName("gridLayout")
        self.approverText = QtWidgets.QLineEdit(self.fileInfo)
        self.approverText.setObjectName("approverText")
        self.gridLayout.addWidget(self.approverText, 3, 4, 1, 1)
        self.approverLable = QtWidgets.QLabel(self.fileInfo)
        self.approverLable.setObjectName("approverLable")
        self.gridLayout.addWidget(self.approverLable, 3, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.fileInfo)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.corporateText = QtWidgets.QLineEdit(self.fileInfo)
        self.corporateText.setObjectName("corporateText")
        self.gridLayout.addWidget(self.corporateText, 0, 2, 1, 1)
        self.managerText = QtWidgets.QLineEdit(self.fileInfo)
        self.managerText.setObjectName("managerText")
        self.gridLayout.addWidget(self.managerText, 0, 4, 1, 1)
        self.managerLable = QtWidgets.QLabel(self.fileInfo)
        self.managerLable.setObjectName("managerLable")
        self.gridLayout.addWidget(self.managerLable, 0, 3, 1, 1)
        self.guandaiLable = QtWidgets.QLabel(self.fileInfo)
        self.guandaiLable.setObjectName("guandaiLable")
        self.gridLayout.addWidget(self.guandaiLable, 1, 1, 1, 1)
        self.guandaiText = QtWidgets.QLineEdit(self.fileInfo)
        self.guandaiText.setObjectName("guandaiText")
        self.gridLayout.addWidget(self.guandaiText, 1, 2, 1, 1)
        self.compilerText = QtWidgets.QLineEdit(self.fileInfo)
        self.compilerText.setObjectName("compilerText")
        self.gridLayout.addWidget(self.compilerText, 1, 4, 1, 1)
        self.compilerLable = QtWidgets.QLabel(self.fileInfo)
        self.compilerLable.setObjectName("compilerLable")
        self.gridLayout.addWidget(self.compilerLable, 1, 3, 1, 1)
        self.auditText = QtWidgets.QLineEdit(self.fileInfo)
        self.auditText.setObjectName("auditText")
        self.gridLayout.addWidget(self.auditText, 3, 2, 1, 1)
        self.auditLable = QtWidgets.QLabel(self.fileInfo)
        self.auditLable.setObjectName("auditLable")
        self.gridLayout.addWidget(self.auditLable, 3, 1, 1, 1)
        self.announcerLable = QtWidgets.QLabel(self.fileInfo)
        self.announcerLable.setObjectName("announcerLable")
        self.gridLayout.addWidget(self.announcerLable, 4, 1, 1, 1)
        self.announcerText = QtWidgets.QLineEdit(self.fileInfo)
        self.announcerText.setObjectName("announcerText")
        self.gridLayout.addWidget(self.announcerText, 4, 2, 1, 1)
        self.gridLayout_7.addWidget(self.fileInfo, 0, 2, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.companyTab)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.logoView = QtWidgets.QGraphicsView(self.groupBox_7)
        self.logoView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.logoView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.logoView.setObjectName("logoView")
        self.gridLayout_13.addWidget(self.logoView, 0, 0, 1, 1)
        self.logoChooseButton = QtWidgets.QToolButton(self.groupBox_7)
        self.logoChooseButton.setObjectName("logoChooseButton")
        self.gridLayout_13.addWidget(self.logoChooseButton, 1, 1, 1, 1)
        self.Logo = QtWidgets.QPlainTextEdit(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Logo.sizePolicy().hasHeightForWidth())
        self.Logo.setSizePolicy(sizePolicy)
        self.Logo.setMinimumSize(QtCore.QSize(0, 40))
        self.Logo.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Logo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Logo.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Logo.setUndoRedoEnabled(False)
        self.Logo.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.Logo.setReadOnly(False)
        self.Logo.setOverwriteMode(True)
        self.Logo.setTextInteractionFlags(QtCore.Qt.TextEditorInteraction)
        self.Logo.setBackgroundVisible(False)
        self.Logo.setObjectName("Logo")
        self.gridLayout_13.addWidget(self.Logo, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_7, 2, 2, 1, 1)
        self.basicInfo = QtWidgets.QGroupBox(self.companyTab)
        self.basicInfo.setObjectName("basicInfo")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.basicInfo)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.companyLable = QtWidgets.QLabel(self.basicInfo)
        self.companyLable.setObjectName("companyLable")
        self.gridLayout_2.addWidget(self.companyLable, 0, 0, 1, 1)
        self.fileNameLable = QtWidgets.QLabel(self.basicInfo)
        self.fileNameLable.setObjectName("fileNameLable")
        self.gridLayout_2.addWidget(self.fileNameLable, 1, 0, 1, 1)
        self.companyText = QtWidgets.QLineEdit(self.basicInfo)
        self.companyText.setObjectName("companyText")
        self.gridLayout_2.addWidget(self.companyText, 0, 3, 1, 1)
        self.introductionLable = QtWidgets.QLabel(self.basicInfo)
        self.introductionLable.setObjectName("introductionLable")
        self.gridLayout_2.addWidget(self.introductionLable, 8, 0, 1, 4)
        self.addressLable = QtWidgets.QLabel(self.basicInfo)
        self.addressLable.setObjectName("addressLable")
        self.gridLayout_2.addWidget(self.addressLable, 2, 0, 1, 1)
        self.introductionText = QtWidgets.QPlainTextEdit(self.basicInfo)
        self.introductionText.setTabChangesFocus(True)
        self.introductionText.setObjectName("introductionText")
        self.gridLayout_2.addWidget(self.introductionText, 9, 0, 1, 4)
        self.coverFieldText = QtWidgets.QLineEdit(self.basicInfo)
        self.coverFieldText.setObjectName("coverFieldText")
        self.gridLayout_2.addWidget(self.coverFieldText, 3, 3, 1, 1)
        self.coverFieldLable = QtWidgets.QLabel(self.basicInfo)
        self.coverFieldLable.setObjectName("coverFieldLable")
        self.gridLayout_2.addWidget(self.coverFieldLable, 3, 0, 1, 1)
        self.policyText = QtWidgets.QLineEdit(self.basicInfo)
        self.policyText.setObjectName("policyText")
        self.gridLayout_2.addWidget(self.policyText, 4, 3, 1, 1)
        self.policyLable = QtWidgets.QLabel(self.basicInfo)
        self.policyLable.setObjectName("policyLable")
        self.gridLayout_2.addWidget(self.policyLable, 4, 0, 1, 1)
        self.fileNameText = QtWidgets.QLineEdit(self.basicInfo)
        self.fileNameText.setObjectName("fileNameText")
        self.gridLayout_2.addWidget(self.fileNameText, 1, 3, 1, 1)
        self.addressText = QtWidgets.QLineEdit(self.basicInfo)
        self.addressText.setObjectName("addressText")
        self.gridLayout_2.addWidget(self.addressText, 2, 3, 1, 1)
        self.zipLable = QtWidgets.QLabel(self.basicInfo)
        self.zipLable.setObjectName("zipLable")
        self.gridLayout_2.addWidget(self.zipLable, 6, 0, 1, 1)
        self.phoneLable = QtWidgets.QLabel(self.basicInfo)
        self.phoneLable.setObjectName("phoneLable")
        self.gridLayout_2.addWidget(self.phoneLable, 7, 0, 1, 1)
        self.zipText = QtWidgets.QLineEdit(self.basicInfo)
        self.zipText.setObjectName("zipText")
        self.gridLayout_2.addWidget(self.zipText, 6, 3, 1, 1)
        self.phoneText = QtWidgets.QLineEdit(self.basicInfo)
        self.phoneText.setObjectName("phoneText")
        self.gridLayout_2.addWidget(self.phoneText, 7, 3, 1, 1)
        self.gridLayout_7.addWidget(self.basicInfo, 0, 1, 5, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.companyTab)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.auditDateLable = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.auditDateLable.sizePolicy().hasHeightForWidth())
        self.auditDateLable.setSizePolicy(sizePolicy)
        self.auditDateLable.setObjectName("auditDateLable")
        self.gridLayout_12.addWidget(self.auditDateLable, 0, 0, 1, 1)
        self.auditDateText = QtWidgets.QDateEdit(self.groupBox_6)
        self.auditDateText.setObjectName("auditDateText")
        self.gridLayout_12.addWidget(self.auditDateText, 0, 1, 1, 1)
        self.releaseDateLable = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.releaseDateLable.sizePolicy().hasHeightForWidth())
        self.releaseDateLable.setSizePolicy(sizePolicy)
        self.releaseDateLable.setObjectName("releaseDateLable")
        self.gridLayout_12.addWidget(self.releaseDateLable, 0, 2, 1, 1)
        self.releaseDateText = QtWidgets.QDateEdit(self.groupBox_6)
        self.releaseDateText.setObjectName("releaseDateText")
        self.gridLayout_12.addWidget(self.releaseDateText, 0, 3, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_6, 1, 2, 1, 1)
        self.tabWidget.addTab(self.companyTab, "")
        self.departmentTab = QtWidgets.QWidget()
        self.departmentTab.setObjectName("departmentTab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.departmentTab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox_4 = QtWidgets.QGroupBox(self.departmentTab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.AddDep = QtWidgets.QPushButton(self.groupBox_4)
        self.AddDep.setObjectName("AddDep")
        self.gridLayout_4.addWidget(self.AddDep, 1, 0, 1, 1)
        self.DeleteDep = QtWidgets.QPushButton(self.groupBox_4)
        self.DeleteDep.setObjectName("DeleteDep")
        self.gridLayout_4.addWidget(self.DeleteDep, 1, 1, 1, 1)
        self.departmentList = QtWidgets.QListWidget(self.groupBox_4)
        self.departmentList.setObjectName("departmentList")
        self.gridLayout_4.addWidget(self.departmentList, 0, 0, 1, 2)
        self.gridLayout_8.addWidget(self.groupBox_4, 0, 0, 3, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.departmentTab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 6, 1, 1)
        self.depLevel = QtWidgets.QSpinBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depLevel.sizePolicy().hasHeightForWidth())
        self.depLevel.setSizePolicy(sizePolicy)
        self.depLevel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.depLevel.setMinimum(1)
        self.depLevel.setMaximum(4)
        self.depLevel.setObjectName("depLevel")
        self.gridLayout_5.addWidget(self.depLevel, 0, 7, 1, 1)
        self.depIntro = QtWidgets.QPlainTextEdit(self.groupBox_5)
        self.depIntro.setTabChangesFocus(True)
        self.depIntro.setObjectName("depIntro")
        self.gridLayout_5.addWidget(self.depIntro, 2, 0, 1, 8)
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_5)
        self.label_27.setObjectName("label_27")
        self.gridLayout_5.addWidget(self.label_27, 1, 0, 1, 1)
        self.depName = QtWidgets.QLineEdit(self.groupBox_5)
        self.depName.setObjectName("depName")
        self.gridLayout_5.addWidget(self.depName, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 2, 1, 1)
        self.leader = QtWidgets.QLineEdit(self.groupBox_5)
        self.leader.setObjectName("leader")
        self.gridLayout_5.addWidget(self.leader, 0, 3, 1, 1)
        self.Operator = QtWidgets.QLineEdit(self.groupBox_5)
        self.Operator.setObjectName("Operator")
        self.gridLayout_5.addWidget(self.Operator, 0, 5, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_5, 0, 1, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(self.departmentTab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.duty_5 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_5.setObjectName("duty_5")
        self.gridLayout_6.addWidget(self.duty_5, 8, 0, 1, 1)
        self.duty_14 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_14.setObjectName("duty_14")
        self.gridLayout_6.addWidget(self.duty_14, 8, 1, 1, 1)
        self.duty_7 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_7.setObjectName("duty_7")
        self.gridLayout_6.addWidget(self.duty_7, 10, 0, 1, 1)
        self.duty_18 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_18.setObjectName("duty_18")
        self.gridLayout_6.addWidget(self.duty_18, 12, 1, 1, 1)
        self.duty_23 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_23.setObjectName("duty_23")
        self.gridLayout_6.addWidget(self.duty_23, 8, 2, 1, 1)
        self.duty_6 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_6.setObjectName("duty_6")
        self.gridLayout_6.addWidget(self.duty_6, 9, 0, 1, 1)
        self.duty_24 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_24.setObjectName("duty_24")
        self.gridLayout_6.addWidget(self.duty_24, 9, 2, 1, 1)
        self.duty_17 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_17.setObjectName("duty_17")
        self.gridLayout_6.addWidget(self.duty_17, 11, 1, 1, 1)
        self.duty_9 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_9.setObjectName("duty_9")
        self.gridLayout_6.addWidget(self.duty_9, 12, 0, 1, 1)
        self.duty_8 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_8.setObjectName("duty_8")
        self.gridLayout_6.addWidget(self.duty_8, 11, 0, 1, 1)
        self.duty_20 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_20.setObjectName("duty_20")
        self.gridLayout_6.addWidget(self.duty_20, 3, 2, 1, 1)
        self.duty_25 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_25.setObjectName("duty_25")
        self.gridLayout_6.addWidget(self.duty_25, 10, 2, 1, 1)
        self.duty_26 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_26.setObjectName("duty_26")
        self.gridLayout_6.addWidget(self.duty_26, 11, 2, 1, 1)
        self.duty_21 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_21.setObjectName("duty_21")
        self.gridLayout_6.addWidget(self.duty_21, 5, 2, 1, 1)
        self.duty_13 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_13.setObjectName("duty_13")
        self.gridLayout_6.addWidget(self.duty_13, 7, 1, 1, 1)
        self.duty_15 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_15.setObjectName("duty_15")
        self.gridLayout_6.addWidget(self.duty_15, 9, 1, 1, 1)
        self.duty_4 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_4.setObjectName("duty_4")
        self.gridLayout_6.addWidget(self.duty_4, 7, 0, 1, 1)
        self.duty_27 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_27.setObjectName("duty_27")
        self.gridLayout_6.addWidget(self.duty_27, 12, 2, 1, 1)
        self.duty_22 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_22.setObjectName("duty_22")
        self.gridLayout_6.addWidget(self.duty_22, 7, 2, 1, 1)
        self.duty_16 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_16.setObjectName("duty_16")
        self.gridLayout_6.addWidget(self.duty_16, 10, 1, 1, 1)
        self.duty_1 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_1.setChecked(False)
        self.duty_1.setObjectName("duty_1")
        self.gridLayout_6.addWidget(self.duty_1, 0, 0, 1, 1)
        self.duty_10 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_10.setObjectName("duty_10")
        self.gridLayout_6.addWidget(self.duty_10, 0, 1, 1, 1)
        self.duty_11 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_11.setObjectName("duty_11")
        self.gridLayout_6.addWidget(self.duty_11, 2, 1, 3, 1)
        self.duty_2 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_2.setObjectName("duty_2")
        self.gridLayout_6.addWidget(self.duty_2, 2, 0, 3, 1)
        self.duty_3 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_3.setObjectName("duty_3")
        self.gridLayout_6.addWidget(self.duty_3, 5, 0, 2, 1)
        self.duty_12 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_12.setObjectName("duty_12")
        self.gridLayout_6.addWidget(self.duty_12, 5, 1, 2, 1)
        self.duty_28 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_28.setObjectName("duty_28")
        self.gridLayout_6.addWidget(self.duty_28, 0, 3, 1, 1)
        self.duty_29 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_29.setObjectName("duty_29")
        self.gridLayout_6.addWidget(self.duty_29, 3, 3, 1, 1)
        self.duty_30 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_30.setObjectName("duty_30")
        self.gridLayout_6.addWidget(self.duty_30, 5, 3, 1, 1)
        self.duty_31 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_31.setObjectName("duty_31")
        self.gridLayout_6.addWidget(self.duty_31, 7, 3, 1, 1)
        self.duty_32 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_32.setObjectName("duty_32")
        self.gridLayout_6.addWidget(self.duty_32, 8, 3, 1, 1)
        self.duty_33 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_33.setObjectName("duty_33")
        self.gridLayout_6.addWidget(self.duty_33, 9, 3, 1, 1)
        self.duty_34 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_34.setObjectName("duty_34")
        self.gridLayout_6.addWidget(self.duty_34, 10, 3, 1, 1)
        self.duty_35 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_35.setObjectName("duty_35")
        self.gridLayout_6.addWidget(self.duty_35, 11, 3, 1, 1)
        self.duty_36 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_36.setObjectName("duty_36")
        self.gridLayout_6.addWidget(self.duty_36, 12, 3, 1, 1)
        self.duty_37 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_37.setObjectName("duty_37")
        self.gridLayout_6.addWidget(self.duty_37, 0, 4, 1, 1)
        self.duty_38 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_38.setObjectName("duty_38")
        self.gridLayout_6.addWidget(self.duty_38, 3, 4, 1, 1)
        self.duty_39 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_39.setObjectName("duty_39")
        self.gridLayout_6.addWidget(self.duty_39, 5, 4, 1, 1)
        self.duty_40 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_40.setObjectName("duty_40")
        self.gridLayout_6.addWidget(self.duty_40, 7, 4, 1, 1)
        self.duty_41 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_41.setObjectName("duty_41")
        self.gridLayout_6.addWidget(self.duty_41, 8, 4, 1, 1)
        self.duty_42 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_42.setObjectName("duty_42")
        self.gridLayout_6.addWidget(self.duty_42, 9, 4, 1, 1)
        self.duty_19 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_19.setObjectName("duty_19")
        self.gridLayout_6.addWidget(self.duty_19, 0, 2, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox, 1, 1, 1, 2)
        self.addOrModifyDep = QtWidgets.QPushButton(self.departmentTab)
        self.addOrModifyDep.setObjectName("addOrModifyDep")
        self.gridLayout_8.addWidget(self.addOrModifyDep, 2, 1, 1, 1)
        self.cancelDep = QtWidgets.QPushButton(self.departmentTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelDep.sizePolicy().hasHeightForWidth())
        self.cancelDep.setSizePolicy(sizePolicy)
        self.cancelDep.setObjectName("cancelDep")
        self.gridLayout_8.addWidget(self.cancelDep, 2, 2, 1, 1)
        self.tabWidget.addTab(self.departmentTab, "")
        self.gridLayout_11.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.level2 = QtWidgets.QGroupBox(self.tab_2)
        self.level2.setObjectName("level2")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.level2)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.level2_fileList = QtWidgets.QTreeWidget(self.level2)
        self.level2_fileList.setObjectName("level2_fileList")
        self.level2_fileList.headerItem().setText(0, "1")
        self.level2_fileList.header().setVisible(False)
        self.gridLayout_14.addWidget(self.level2_fileList, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.level2, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.level3_fileList = QtWidgets.QTreeWidget(self.groupBox_8)
        self.level3_fileList.setObjectName("level3_fileList")
        self.level3_fileList.headerItem().setText(0, "1")
        self.level3_fileList.header().setVisible(False)
        self.gridLayout_17.addWidget(self.level3_fileList, 0, 0, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_8, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_4)
        self.tabWidget_3.setGeometry(QtCore.QRect(10, 10, 941, 721))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.listWidget = QtWidgets.QListWidget(self.tab_5)
        self.listWidget.setGeometry(QtCore.QRect(10, 10, 191, 671))
        self.listWidget.setObjectName("listWidget")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_5)
        self.tabWidget_4.setGeometry(QtCore.QRect(210, 10, 711, 661))
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 10, 331, 291))
        self.groupBox_9.setObjectName("groupBox_9")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit.setGeometry(QtCore.QRect(80, 30, 231, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 60, 231, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_3.setGeometry(QtCore.QRect(80, 90, 231, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_4.setGeometry(QtCore.QRect(80, 120, 231, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_5.setGeometry(QtCore.QRect(80, 150, 231, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_9)
        self.label_6.setGeometry(QtCore.QRect(20, 30, 54, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_9)
        self.label_7.setGeometry(QtCore.QRect(20, 60, 54, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_9)
        self.label_8.setGeometry(QtCore.QRect(20, 120, 54, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_9)
        self.label_9.setGeometry(QtCore.QRect(10, 90, 61, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_9)
        self.label_10.setGeometry(QtCore.QRect(20, 150, 54, 21))
        self.label_10.setObjectName("label_10")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_10.setGeometry(QtCore.QRect(360, 10, 341, 291))
        self.groupBox_10.setObjectName("groupBox_10")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_6.setGeometry(QtCore.QRect(110, 20, 191, 21))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_7.setGeometry(QtCore.QRect(110, 50, 191, 21))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_8.setGeometry(QtCore.QRect(110, 80, 191, 21))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_9.setGeometry(QtCore.QRect(110, 110, 191, 21))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_10.setGeometry(QtCore.QRect(110, 140, 191, 21))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_11.setGeometry(QtCore.QRect(110, 170, 191, 21))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_12.setGeometry(QtCore.QRect(110, 200, 191, 21))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_11 = QtWidgets.QLabel(self.groupBox_10)
        self.label_11.setGeometry(QtCore.QRect(20, 20, 61, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_10)
        self.label_12.setGeometry(QtCore.QRect(10, 50, 91, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_10)
        self.label_13.setGeometry(QtCore.QRect(10, 80, 91, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_10)
        self.label_14.setGeometry(QtCore.QRect(13, 140, 91, 21))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_10)
        self.label_15.setGeometry(QtCore.QRect(13, 110, 91, 21))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_10)
        self.label_16.setGeometry(QtCore.QRect(13, 200, 91, 21))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_10)
        self.label_17.setGeometry(QtCore.QRect(13, 170, 91, 21))
        self.label_17.setObjectName("label_17")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 310, 321, 321))
        self.groupBox_11.setObjectName("groupBox_11")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_17.setGeometry(QtCore.QRect(90, 30, 221, 21))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_18.setGeometry(QtCore.QRect(90, 60, 221, 21))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_19.setGeometry(QtCore.QRect(90, 90, 221, 21))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_20.setGeometry(QtCore.QRect(90, 120, 221, 21))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_21.setGeometry(QtCore.QRect(90, 150, 221, 21))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_22.setGeometry(QtCore.QRect(90, 180, 221, 21))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_23.setGeometry(QtCore.QRect(90, 210, 221, 21))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_24.setGeometry(QtCore.QRect(90, 240, 221, 21))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.label_18 = QtWidgets.QLabel(self.groupBox_11)
        self.label_18.setGeometry(QtCore.QRect(20, 30, 54, 21))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_11)
        self.label_19.setGeometry(QtCore.QRect(10, 60, 61, 21))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_11)
        self.label_20.setGeometry(QtCore.QRect(10, 90, 101, 21))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_11)
        self.label_21.setGeometry(QtCore.QRect(20, 150, 54, 21))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_11)
        self.label_22.setGeometry(QtCore.QRect(20, 120, 54, 21))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_11)
        self.label_23.setGeometry(QtCore.QRect(20, 180, 54, 21))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_11)
        self.label_24.setGeometry(QtCore.QRect(10, 240, 81, 21))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.groupBox_11)
        self.label_25.setGeometry(QtCore.QRect(20, 210, 54, 21))
        self.label_25.setObjectName("label_25")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_12.setGeometry(QtCore.QRect(340, 310, 321, 321))
        self.groupBox_12.setObjectName("groupBox_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_13.setGeometry(QtCore.QRect(100, 30, 211, 21))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_14.setGeometry(QtCore.QRect(100, 60, 211, 21))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_15.setGeometry(QtCore.QRect(100, 90, 211, 21))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_16.setGeometry(QtCore.QRect(100, 120, 211, 21))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.label_26 = QtWidgets.QLabel(self.groupBox_12)
        self.label_26.setGeometry(QtCore.QRect(10, 30, 81, 21))
        self.label_26.setObjectName("label_26")
        self.label_28 = QtWidgets.QLabel(self.groupBox_12)
        self.label_28.setGeometry(QtCore.QRect(10, 60, 81, 21))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.groupBox_12)
        self.label_29.setGeometry(QtCore.QRect(10, 90, 81, 21))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.groupBox_12)
        self.label_30.setGeometry(QtCore.QRect(10, 120, 81, 21))
        self.label_30.setObjectName("label_30")
        self.tabWidget_4.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_13.setGeometry(QtCore.QRect(10, 10, 331, 321))
        self.groupBox_13.setObjectName("groupBox_13")
        self.label_31 = QtWidgets.QLabel(self.groupBox_13)
        self.label_31.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_31.setObjectName("label_31")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_13)
        self.textEdit.setGeometry(QtCore.QRect(10, 40, 181, 101))
        self.textEdit.setObjectName("textEdit")
        self.label_32 = QtWidgets.QLabel(self.groupBox_13)
        self.label_32.setGeometry(QtCore.QRect(10, 150, 111, 16))
        self.label_32.setObjectName("label_32")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_13)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 170, 181, 71))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_33 = QtWidgets.QLabel(self.groupBox_13)
        self.label_33.setGeometry(QtCore.QRect(10, 270, 81, 16))
        self.label_33.setObjectName("label_33")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_25.setGeometry(QtCore.QRect(10, 290, 181, 20))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_14.setGeometry(QtCore.QRect(10, 340, 331, 281))
        self.groupBox_14.setObjectName("groupBox_14")
        self.label_34 = QtWidgets.QLabel(self.groupBox_14)
        self.label_34.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.groupBox_14)
        self.label_35.setGeometry(QtCore.QRect(10, 50, 81, 21))
        self.label_35.setObjectName("label_35")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.groupBox_14)
        self.lineEdit_26.setGeometry(QtCore.QRect(90, 50, 113, 20))
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.groupBox_14)
        self.lineEdit_27.setGeometry(QtCore.QRect(90, 20, 113, 20))
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.label_36 = QtWidgets.QLabel(self.groupBox_14)
        self.label_36.setGeometry(QtCore.QRect(10, 80, 71, 16))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.groupBox_14)
        self.label_37.setGeometry(QtCore.QRect(10, 110, 71, 16))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.groupBox_14)
        self.label_38.setGeometry(QtCore.QRect(10, 140, 71, 16))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.groupBox_14)
        self.label_39.setGeometry(QtCore.QRect(10, 170, 131, 16))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.groupBox_14)
        self.label_40.setGeometry(QtCore.QRect(10, 200, 81, 16))
        self.label_40.setObjectName("label_40")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_14)
        self.spinBox.setGeometry(QtCore.QRect(100, 110, 42, 16))
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_14)
        self.spinBox_2.setGeometry(QtCore.QRect(100, 140, 42, 16))
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox_14)
        self.spinBox_3.setGeometry(QtCore.QRect(150, 170, 42, 16))
        self.spinBox_3.setObjectName("spinBox_3")
        self.spinBox_4 = QtWidgets.QSpinBox(self.groupBox_14)
        self.spinBox_4.setGeometry(QtCore.QRect(100, 200, 42, 16))
        self.spinBox_4.setObjectName("spinBox_4")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_14)
        self.comboBox.setGeometry(QtCore.QRect(90, 80, 81, 21))
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.groupBox_15 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_15.setGeometry(QtCore.QRect(350, 10, 351, 601))
        self.groupBox_15.setObjectName("groupBox_15")
        self.label_41 = QtWidgets.QLabel(self.groupBox_15)
        self.label_41.setGeometry(QtCore.QRect(10, 20, 54, 12))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.groupBox_15)
        self.label_42.setGeometry(QtCore.QRect(10, 50, 54, 12))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.groupBox_15)
        self.label_43.setGeometry(QtCore.QRect(10, 80, 54, 12))
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.groupBox_15)
        self.label_44.setGeometry(QtCore.QRect(10, 110, 54, 12))
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.groupBox_15)
        self.label_45.setGeometry(QtCore.QRect(10, 140, 54, 12))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.groupBox_15)
        self.label_46.setGeometry(QtCore.QRect(10, 170, 71, 16))
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.groupBox_15)
        self.label_47.setGeometry(QtCore.QRect(10, 200, 54, 12))
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.groupBox_15)
        self.label_48.setGeometry(QtCore.QRect(10, 230, 61, 16))
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.groupBox_15)
        self.label_49.setGeometry(QtCore.QRect(10, 260, 54, 12))
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.groupBox_15)
        self.label_50.setGeometry(QtCore.QRect(10, 290, 71, 16))
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.groupBox_15)
        self.label_51.setGeometry(QtCore.QRect(10, 320, 54, 12))
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.groupBox_15)
        self.label_52.setGeometry(QtCore.QRect(10, 350, 54, 12))
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.groupBox_15)
        self.label_53.setGeometry(QtCore.QRect(10, 380, 71, 16))
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.groupBox_15)
        self.label_54.setGeometry(QtCore.QRect(10, 410, 54, 12))
        self.label_54.setObjectName("label_54")
        self.tabWidget_4.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.groupBox_18 = QtWidgets.QGroupBox(self.tab_9)
        self.groupBox_18.setGeometry(QtCore.QRect(340, 10, 321, 611))
        self.groupBox_18.setObjectName("groupBox_18")
        self.label_62 = QtWidgets.QLabel(self.groupBox_18)
        self.label_62.setGeometry(QtCore.QRect(10, 20, 54, 12))
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.groupBox_18)
        self.label_63.setGeometry(QtCore.QRect(10, 50, 54, 12))
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.groupBox_18)
        self.label_64.setGeometry(QtCore.QRect(10, 80, 54, 12))
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.groupBox_18)
        self.label_65.setGeometry(QtCore.QRect(10, 110, 54, 12))
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.groupBox_18)
        self.label_66.setGeometry(QtCore.QRect(10, 140, 81, 16))
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.groupBox_18)
        self.label_67.setGeometry(QtCore.QRect(10, 170, 81, 16))
        self.label_67.setObjectName("label_67")
        self.label_68 = QtWidgets.QLabel(self.groupBox_18)
        self.label_68.setGeometry(QtCore.QRect(10, 200, 111, 16))
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(self.groupBox_18)
        self.label_69.setGeometry(QtCore.QRect(10, 310, 101, 16))
        self.label_69.setObjectName("label_69")
        self.label_70 = QtWidgets.QLabel(self.groupBox_18)
        self.label_70.setGeometry(QtCore.QRect(10, 460, 61, 16))
        self.label_70.setObjectName("label_70")
        self.label_71 = QtWidgets.QLabel(self.groupBox_18)
        self.label_71.setGeometry(QtCore.QRect(10, 490, 81, 16))
        self.label_71.setObjectName("label_71")
        self.label_72 = QtWidgets.QLabel(self.groupBox_18)
        self.label_72.setGeometry(QtCore.QRect(10, 520, 61, 16))
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QLabel(self.groupBox_18)
        self.label_73.setGeometry(QtCore.QRect(10, 550, 81, 16))
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QLabel(self.groupBox_18)
        self.label_74.setGeometry(QtCore.QRect(10, 580, 71, 16))
        self.label_74.setObjectName("label_74")
        self.groupBox_16 = QtWidgets.QGroupBox(self.tab_9)
        self.groupBox_16.setGeometry(QtCore.QRect(0, 10, 321, 301))
        self.groupBox_16.setObjectName("groupBox_16")
        self.label_55 = QtWidgets.QLabel(self.groupBox_16)
        self.label_55.setGeometry(QtCore.QRect(10, 20, 111, 16))
        self.label_55.setObjectName("label_55")
        self.textEdit_3 = QtWidgets.QTextEdit(self.groupBox_16)
        self.textEdit_3.setGeometry(QtCore.QRect(10, 40, 301, 51))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_56 = QtWidgets.QLabel(self.groupBox_16)
        self.label_56.setGeometry(QtCore.QRect(10, 100, 111, 16))
        self.label_56.setObjectName("label_56")
        self.textEdit_4 = QtWidgets.QTextEdit(self.groupBox_16)
        self.textEdit_4.setGeometry(QtCore.QRect(10, 120, 301, 51))
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_57 = QtWidgets.QLabel(self.groupBox_16)
        self.label_57.setGeometry(QtCore.QRect(10, 180, 54, 12))
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.groupBox_16)
        self.label_58.setGeometry(QtCore.QRect(10, 210, 91, 16))
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.groupBox_16)
        self.label_59.setGeometry(QtCore.QRect(10, 240, 91, 16))
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.groupBox_16)
        self.label_60.setGeometry(QtCore.QRect(10, 270, 81, 16))
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.groupBox_16)
        self.label_61.setGeometry(QtCore.QRect(10, 300, 81, 16))
        self.label_61.setObjectName("label_61")
        self.groupBox_17 = QtWidgets.QGroupBox(self.tab_9)
        self.groupBox_17.setGeometry(QtCore.QRect(0, 320, 321, 301))
        self.groupBox_17.setObjectName("groupBox_17")
        self.tabWidget_4.addTab(self.tab_9, "")
        self.tabWidget_3.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget_3.addTab(self.tab_6, "")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.gridLayout_3.addWidget(self.tabWidget_2, 1, 0, 1, 5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actioncaidan = QtWidgets.QAction(MainWindow)
        self.actioncaidan.setObjectName("actioncaidan")
        self.actionsetting = QtWidgets.QAction(MainWindow)
        self.actionsetting.setObjectName("actionsetting")
        self.actioncaocun = QtWidgets.QAction(MainWindow)
        self.actioncaocun.setObjectName("actioncaocun")
        self.actionmuban = QtWidgets.QAction(MainWindow)
        self.actionmuban.setObjectName("actionmuban")
        self.actiontuichu = QtWidgets.QAction(MainWindow)
        self.actiontuichu.setObjectName("actiontuichu")
        self.actionbaocunlujing = QtWidgets.QAction(MainWindow)
        self.actionbaocunlujing.setObjectName("actionbaocunlujing")
        self.actiontuichu_2 = QtWidgets.QAction(MainWindow)
        self.actiontuichu_2.setObjectName("actiontuichu_2")

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(3)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(1)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.searchContent, self.searchButton)
        MainWindow.setTabOrder(self.searchButton, self.companyText)
        MainWindow.setTabOrder(self.companyText, self.fileNameText)
        MainWindow.setTabOrder(self.fileNameText, self.addressText)
        MainWindow.setTabOrder(self.addressText, self.coverFieldText)
        MainWindow.setTabOrder(self.coverFieldText, self.policyText)
        MainWindow.setTabOrder(self.policyText, self.zipText)
        MainWindow.setTabOrder(self.zipText, self.phoneText)
        MainWindow.setTabOrder(self.phoneText, self.introductionText)
        MainWindow.setTabOrder(self.introductionText, self.corporateText)
        MainWindow.setTabOrder(self.corporateText, self.managerText)
        MainWindow.setTabOrder(self.managerText, self.guandaiText)
        MainWindow.setTabOrder(self.guandaiText, self.compilerText)
        MainWindow.setTabOrder(self.compilerText, self.auditText)
        MainWindow.setTabOrder(self.auditText, self.approverText)
        MainWindow.setTabOrder(self.approverText, self.announcerText)
        MainWindow.setTabOrder(self.announcerText, self.logoChooseButton)
        MainWindow.setTabOrder(self.logoChooseButton, self.auditDateText)
        MainWindow.setTabOrder(self.auditDateText, self.releaseDateText)
        MainWindow.setTabOrder(self.releaseDateText, self.level1Border)
        MainWindow.setTabOrder(self.level1Border, self.level1Font)
        MainWindow.setTabOrder(self.level1Font, self.level1Width)
        MainWindow.setTabOrder(self.level1Width, self.level2Border)
        MainWindow.setTabOrder(self.level2Border, self.level2Font)
        MainWindow.setTabOrder(self.level2Font, self.level2Width)
        MainWindow.setTabOrder(self.level2Width, self.level3Border)
        MainWindow.setTabOrder(self.level3Border, self.level3Font)
        MainWindow.setTabOrder(self.level3Font, self.level3Width)
        MainWindow.setTabOrder(self.level3Width, self.level4Border)
        MainWindow.setTabOrder(self.level4Border, self.level4Font)
        MainWindow.setTabOrder(self.level4Font, self.level4Width)
        MainWindow.setTabOrder(self.level4Width, self.previewButton)
        MainWindow.setTabOrder(self.previewButton, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.AddDep)
        MainWindow.setTabOrder(self.AddDep, self.DeleteDep)
        MainWindow.setTabOrder(self.DeleteDep, self.depName)
        MainWindow.setTabOrder(self.depName, self.depLevel)
        MainWindow.setTabOrder(self.depLevel, self.depIntro)
        MainWindow.setTabOrder(self.depIntro, self.duty_1)
        MainWindow.setTabOrder(self.duty_1, self.duty_2)
        MainWindow.setTabOrder(self.duty_2, self.duty_3)
        MainWindow.setTabOrder(self.duty_3, self.duty_4)
        MainWindow.setTabOrder(self.duty_4, self.duty_5)
        MainWindow.setTabOrder(self.duty_5, self.duty_6)
        MainWindow.setTabOrder(self.duty_6, self.duty_7)
        MainWindow.setTabOrder(self.duty_7, self.duty_8)
        MainWindow.setTabOrder(self.duty_8, self.duty_9)
        MainWindow.setTabOrder(self.duty_9, self.duty_10)
        MainWindow.setTabOrder(self.duty_10, self.duty_11)
        MainWindow.setTabOrder(self.duty_11, self.duty_12)
        MainWindow.setTabOrder(self.duty_12, self.duty_13)
        MainWindow.setTabOrder(self.duty_13, self.duty_14)
        MainWindow.setTabOrder(self.duty_14, self.duty_15)
        MainWindow.setTabOrder(self.duty_15, self.duty_16)
        MainWindow.setTabOrder(self.duty_16, self.duty_17)
        MainWindow.setTabOrder(self.duty_17, self.duty_18)
        MainWindow.setTabOrder(self.duty_18, self.duty_19)
        MainWindow.setTabOrder(self.duty_19, self.duty_20)
        MainWindow.setTabOrder(self.duty_20, self.duty_21)
        MainWindow.setTabOrder(self.duty_21, self.duty_22)
        MainWindow.setTabOrder(self.duty_22, self.duty_23)
        MainWindow.setTabOrder(self.duty_23, self.duty_24)
        MainWindow.setTabOrder(self.duty_24, self.duty_25)
        MainWindow.setTabOrder(self.duty_25, self.duty_26)
        MainWindow.setTabOrder(self.duty_26, self.duty_27)
        MainWindow.setTabOrder(self.duty_27, self.duty_28)
        MainWindow.setTabOrder(self.duty_28, self.duty_29)
        MainWindow.setTabOrder(self.duty_29, self.duty_30)
        MainWindow.setTabOrder(self.duty_30, self.duty_31)
        MainWindow.setTabOrder(self.duty_31, self.duty_32)
        MainWindow.setTabOrder(self.duty_32, self.duty_33)
        MainWindow.setTabOrder(self.duty_33, self.duty_34)
        MainWindow.setTabOrder(self.duty_34, self.duty_35)
        MainWindow.setTabOrder(self.duty_35, self.duty_36)
        MainWindow.setTabOrder(self.duty_36, self.duty_37)
        MainWindow.setTabOrder(self.duty_37, self.duty_38)
        MainWindow.setTabOrder(self.duty_38, self.duty_39)
        MainWindow.setTabOrder(self.duty_39, self.duty_40)
        MainWindow.setTabOrder(self.duty_40, self.duty_41)
        MainWindow.setTabOrder(self.duty_41, self.duty_42)
        MainWindow.setTabOrder(self.duty_42, self.addOrModifyDep)
        MainWindow.setTabOrder(self.addOrModifyDep, self.cancelDep)
        MainWindow.setTabOrder(self.cancelDep, self.tabWidget_2)
        MainWindow.setTabOrder(self.tabWidget_2, self.saveButton)
        MainWindow.setTabOrder(self.saveButton, self.createBotton)
        MainWindow.setTabOrder(self.createBotton, self.cancelButton)
        MainWindow.setTabOrder(self.cancelButton, self.previewPic)
        MainWindow.setTabOrder(self.previewPic, self.logoView)
        MainWindow.setTabOrder(self.logoView, self.departmentList)
        MainWindow.setTabOrder(self.departmentList, self.Logo)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "信息技术服务管理文件平台 v1.1"))
        self.searchButton.setText(_translate("MainWindow", "搜索"))
        self.saveButton.setText(_translate("MainWindow", "保存"))
        self.createBotton.setText(_translate("MainWindow", "文档生成"))
        self.cancelButton.setText(_translate("MainWindow", "放弃修改"))
        self.groupBox_3.setTitle(_translate("MainWindow", "部门结构图"))
        self.depStructLable.setText(_translate("MainWindow", "部门结构"))
        self.previewButton.setText(_translate("MainWindow", "预览图片"))
        self.groupBox_2.setTitle(_translate("MainWindow", "样式"))
        self.borderLable.setText(_translate("MainWindow", "边框"))
        self.fontLable.setText(_translate("MainWindow", "字体"))
        self.level1Lable.setText(_translate("MainWindow", "第一层"))
        self.level2Lable.setText(_translate("MainWindow", "第二层"))
        self.level3Lable.setText(_translate("MainWindow", "第三层"))
        self.level4Lable.setText(_translate("MainWindow", "第四层"))
        self.heightLable.setText(_translate("MainWindow", "行宽"))
        self.fileInfo.setTitle(_translate("MainWindow", "公司（组织级人员）信息"))
        self.approverLable.setText(_translate("MainWindow", "批准人"))
        self.label_3.setText(_translate("MainWindow", "法人代表"))
        self.managerLable.setText(_translate("MainWindow", "总经理"))
        self.guandaiLable.setText(_translate("MainWindow", "管理者代表"))
        self.compilerLable.setText(_translate("MainWindow", "编制人"))
        self.auditLable.setText(_translate("MainWindow", "审核人"))
        self.announcerLable.setText(_translate("MainWindow", "发布人"))
        self.groupBox_7.setTitle(_translate("MainWindow", "公司图标"))
        self.logoChooseButton.setText(_translate("MainWindow", "..."))
        self.Logo.setPlaceholderText(_translate("MainWindow", "请将公司图标拖拽至此或点击右边的选择按钮"))
        self.basicInfo.setTitle(_translate("MainWindow", "公司基础信息"))
        self.companyLable.setText(_translate("MainWindow", "公司名称"))
        self.fileNameLable.setText(_translate("MainWindow", "公司缩写"))
        self.introductionLable.setText(_translate("MainWindow", "公司简介"))
        self.addressLable.setText(_translate("MainWindow", "通信地址"))
        self.coverFieldLable.setText(_translate("MainWindow", "覆盖范围"))
        self.policyLable.setText(_translate("MainWindow", "服务方针"))
        self.zipLable.setText(_translate("MainWindow", "公司邮编"))
        self.phoneLable.setText(_translate("MainWindow", "公司电话"))
        self.groupBox_6.setTitle(_translate("MainWindow", "文档日期输入"))
        self.auditDateLable.setText(_translate("MainWindow", "编制日期"))
        self.auditDateText.setDisplayFormat(_translate("MainWindow", "yyyy年MM月dd日"))
        self.releaseDateLable.setText(_translate("MainWindow", "实施日期"))
        self.releaseDateText.setDisplayFormat(_translate("MainWindow", "yyyy年MM月dd日"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.companyTab), _translate("MainWindow", "公司信息"))
        self.groupBox_4.setTitle(_translate("MainWindow", "部门列表"))
        self.AddDep.setText(_translate("MainWindow", "添加"))
        self.DeleteDep.setText(_translate("MainWindow", "删除"))
        self.groupBox_5.setTitle(_translate("MainWindow", "部门信息"))
        self.label_5.setText(_translate("MainWindow", "经办人"))
        self.label.setText(_translate("MainWindow", "部门级别"))
        self.label_2.setText(_translate("MainWindow", "部门名称"))
        self.label_27.setText(_translate("MainWindow", "部门简介"))
        self.label_4.setText(_translate("MainWindow", "负责人"))
        self.groupBox.setTitle(_translate("MainWindow", "部门职责"))
        self.duty_5.setText(_translate("MainWindow", "4.1.3 权限、职\n"
"责和沟通"))
        self.duty_14.setText(_translate("MainWindow", "4.4.2 人力资源"))
        self.duty_7.setText(_translate("MainWindow", "4.2 治理由其他方\n"
"运行的过程"))
        self.duty_18.setText(_translate("MainWindow", "4.5.3 实施和运\n"
"行服务管理体系\n"
"（Do）"))
        self.duty_23.setText(_translate("MainWindow", "4.5.5 维护和改进\n"
"服务管理体系\n"
"（Act）"))
        self.duty_6.setText(_translate("MainWindow", "4.1.4 管理者代\n"
"表"))
        self.duty_24.setText(_translate("MainWindow", "4.5.5.1 总要求"))
        self.duty_17.setText(_translate("MainWindow", "4.5.2 策划服务\n"
"管理体系（Plan）"))
        self.duty_9.setText(_translate("MainWindow", "4.3.1 文件的建立\n"
"和维护"))
        self.duty_8.setText(_translate("MainWindow", "4.3 文件管理"))
        self.duty_20.setText(_translate("MainWindow", "4.5.4.1 总要求"))
        self.duty_25.setText(_translate("MainWindow", "4.5.5.2 管理改进"))
        self.duty_26.setText(_translate("MainWindow", "5.1 总要求"))
        self.duty_21.setText(_translate("MainWindow", "4.5.4.2 内部审\n"
"核"))
        self.duty_13.setText(_translate("MainWindow", "4.4.1 资源提供"))
        self.duty_15.setText(_translate("MainWindow", "4.5 建立和改进\n"
"服务管理体系\n"
"（SMS）"))
        self.duty_4.setText(_translate("MainWindow", "4.1.2 服务管理方\n"
"针"))
        self.duty_27.setText(_translate("MainWindow", "5.2 策划新的或变\n"
"更的服务"))
        self.duty_22.setText(_translate("MainWindow", "4.5.4.3 管理评审"))
        self.duty_16.setText(_translate("MainWindow", "4.5.1 定义范围"))
        self.duty_1.setText(_translate("MainWindow", "4 管理体系要求"))
        self.duty_10.setText(_translate("MainWindow", "4.3.2 文件控制"))
        self.duty_11.setText(_translate("MainWindow", "4.3.3 记录控制"))
        self.duty_2.setText(_translate("MainWindow", "4.1 管理职责"))
        self.duty_3.setText(_translate("MainWindow", "4.1.1 管理承诺"))
        self.duty_12.setText(_translate("MainWindow", "4.4 资源管理"))
        self.duty_28.setText(_translate("MainWindow", "5.3 设计和开发新\n"
"的或变更的服务"))
        self.duty_29.setText(_translate("MainWindow", "5.4 新的或变更的\n"
"服务转换"))
        self.duty_30.setText(_translate("MainWindow", "6.1 服务级别管理"))
        self.duty_31.setText(_translate("MainWindow", "6.2 服务报告管\n"
"理"))
        self.duty_32.setText(_translate("MainWindow", "6.3 服务的连续性\n"
"可用性管理"))
        self.duty_33.setText(_translate("MainWindow", "6.4 服务的预算和\n"
"核算"))
        self.duty_34.setText(_translate("MainWindow", "6.5 能力管理"))
        self.duty_35.setText(_translate("MainWindow", "6.6 信息安全"))
        self.duty_36.setText(_translate("MainWindow", "7.1 业务关系管理"))
        self.duty_37.setText(_translate("MainWindow", "7.2 供应商管理"))
        self.duty_38.setText(_translate("MainWindow", "8.1 事件和服务请\n"
"求管理"))
        self.duty_39.setText(_translate("MainWindow", "8.2 问题管理"))
        self.duty_40.setText(_translate("MainWindow", "9.1 配置管理"))
        self.duty_41.setText(_translate("MainWindow", "9.2 变更管理"))
        self.duty_42.setText(_translate("MainWindow", "9.3 发布和部署管\n"
"理"))
        self.duty_19.setText(_translate("MainWindow", "4.5.4 监视和评\n"
"审服务管理体系\n"
"（Check）"))
        self.addOrModifyDep.setText(_translate("MainWindow", "保存修改"))
        self.cancelDep.setText(_translate("MainWindow", "放弃修改"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.departmentTab), _translate("MainWindow", "部门信息"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "一层文件"))
        self.level2.setTitle(_translate("MainWindow", "二层文件列表"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "二层文件"))
        self.groupBox_8.setTitle(_translate("MainWindow", "三层文件列表"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "三层文件"))
        self.groupBox_9.setTitle(_translate("MainWindow", "甲方信息"))
        self.label_6.setText(_translate("MainWindow", "项目名称"))
        self.label_7.setText(_translate("MainWindow", "甲方名称"))
        self.label_8.setText(_translate("MainWindow", "联系电话"))
        self.label_9.setText(_translate("MainWindow", "联系人姓名"))
        self.label_10.setText(_translate("MainWindow", "联系地址"))
        self.groupBox_10.setTitle(_translate("MainWindow", "乙方信息"))
        self.label_11.setText(_translate("MainWindow", "联系人姓名"))
        self.label_12.setText(_translate("MainWindow", "服务联系人姓名"))
        self.label_13.setText(_translate("MainWindow", "服务联系人邮箱"))
        self.label_14.setText(_translate("MainWindow", "服务投诉人姓名"))
        self.label_15.setText(_translate("MainWindow", "服务联系人手机"))
        self.label_16.setText(_translate("MainWindow", "服务投诉人手机"))
        self.label_17.setText(_translate("MainWindow", "服务投诉人邮箱"))
        self.groupBox_11.setTitle(_translate("MainWindow", "项目服务内容信息"))
        self.label_18.setText(_translate("MainWindow", "项目金额"))
        self.label_19.setText(_translate("MainWindow", "项目有效期"))
        self.label_20.setText(_translate("MainWindow", "服务配置项"))
        self.label_21.setText(_translate("MainWindow", "服务级别"))
        self.label_22.setText(_translate("MainWindow", "服务名称"))
        self.label_23.setText(_translate("MainWindow", "服务内容"))
        self.label_24.setText(_translate("MainWindow", "服务时间要求"))
        self.label_25.setText(_translate("MainWindow", "服务要求"))
        self.groupBox_12.setTitle(_translate("MainWindow", "项目服务团队信息"))
        self.label_26.setText(_translate("MainWindow", "项目启动时间"))
        self.label_28.setText(_translate("MainWindow", "项目需求分析"))
        self.label_29.setText(_translate("MainWindow", "项目经理"))
        self.label_30.setText(_translate("MainWindow", "项目技术经理"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_7), _translate("MainWindow", "项目基础信息"))
        self.groupBox_13.setTitle(_translate("MainWindow", "服务报告"))
        self.label_31.setText(_translate("MainWindow", "服务报告期"))
        self.label_32.setText(_translate("MainWindow", "下阶段重点工作内容"))
        self.label_33.setText(_translate("MainWindow", "服务回访日期"))
        self.groupBox_14.setTitle(_translate("MainWindow", "事件与问题管理"))
        self.label_34.setText(_translate("MainWindow", "事件管理经理"))
        self.label_35.setText(_translate("MainWindow", "问题管理经理"))
        self.label_36.setText(_translate("MainWindow", "受理事件等级"))
        self.label_37.setText(_translate("MainWindow", "受理事件件数"))
        self.label_38.setText(_translate("MainWindow", "关闭事件件数"))
        self.label_39.setText(_translate("MainWindow", "转化为问题的事件件数"))
        self.label_40.setText(_translate("MainWindow", "汇总问题件数"))
        self.comboBox.setItemText(0, _translate("MainWindow", "S1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "S2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "S3"))
        self.comboBox.setItemText(3, _translate("MainWindow", "S4"))
        self.groupBox_15.setTitle(_translate("MainWindow", "配置、变更、发布管理"))
        self.label_41.setText(_translate("MainWindow", "变更经理"))
        self.label_42.setText(_translate("MainWindow", "配置经理"))
        self.label_43.setText(_translate("MainWindow", "发布经理"))
        self.label_44.setText(_translate("MainWindow", "关系经理"))
        self.label_45.setText(_translate("MainWindow", "配置版本"))
        self.label_46.setText(_translate("MainWindow", "配置发布日期"))
        self.label_47.setText(_translate("MainWindow", "变更数量"))
        self.label_48.setText(_translate("MainWindow", "发布总数量"))
        self.label_49.setText(_translate("MainWindow", "发布日期"))
        self.label_50.setText(_translate("MainWindow", "发布申请日期"))
        self.label_51.setText(_translate("MainWindow", "发布单号"))
        self.label_52.setText(_translate("MainWindow", "发布目标"))
        self.label_53.setText(_translate("MainWindow", "发布交付物"))
        self.label_54.setText(_translate("MainWindow", "发布版本"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_8), _translate("MainWindow", "服务过程管理信息1"))
        self.groupBox_18.setTitle(_translate("MainWindow", "文件与记录管理"))
        self.label_62.setText(_translate("MainWindow", "审计对象"))
        self.label_63.setText(_translate("MainWindow", "审计时间"))
        self.label_64.setText(_translate("MainWindow", "审计人员"))
        self.label_65.setText(_translate("MainWindow", "审计安排"))
        self.label_66.setText(_translate("MainWindow", "文件审批内容"))
        self.label_67.setText(_translate("MainWindow", "审批文件名称"))
        self.label_68.setText(_translate("MainWindow", "审批文件审核内容"))
        self.label_69.setText(_translate("MainWindow", "审批文件过程简述"))
        self.label_70.setText(_translate("MainWindow", "文件审批人"))
        self.label_71.setText(_translate("MainWindow", "文件审批日期"))
        self.label_72.setText(_translate("MainWindow", "文件批准人"))
        self.label_73.setText(_translate("MainWindow", "文件批准日期"))
        self.label_74.setText(_translate("MainWindow", "文件发放人"))
        self.groupBox_16.setTitle(_translate("MainWindow", "连续性管理"))
        self.label_55.setText(_translate("MainWindow", "连续性测试经过内容"))
        self.label_56.setText(_translate("MainWindow", "连续性测试结果内容"))
        self.label_57.setText(_translate("MainWindow", "测试日期"))
        self.label_58.setText(_translate("MainWindow", "可用性技术人员"))
        self.label_59.setText(_translate("MainWindow", "可用性审批人员"))
        self.label_60.setText(_translate("MainWindow", "记录编制时间"))
        self.label_61.setText(_translate("MainWindow", "记录审核时间"))
        self.groupBox_17.setTitle(_translate("MainWindow", "审核管理"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_9), _translate("MainWindow", "服务过程管理信息2"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_5), _translate("MainWindow", "四层项目"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("MainWindow", "四层组织"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "四层文件"))
        self.actioncaidan.setText(_translate("MainWindow", "数据库配置"))
        self.actionsetting.setText(_translate("MainWindow", "setting"))
        self.actioncaocun.setText(_translate("MainWindow", "caocun"))
        self.actionmuban.setText(_translate("MainWindow", "模板选择"))
        self.actiontuichu.setText(_translate("MainWindow", "tuichu"))
        self.actionbaocunlujing.setText(_translate("MainWindow", "保存路径"))
        self.actiontuichu_2.setText(_translate("MainWindow", "退出"))

