# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1013, 820)
        MainWindow.setMinimumSize(QtCore.QSize(1013, 820))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.searchContent = QtWidgets.QLineEdit(self.centralwidget)
        self.searchContent.setClearButtonEnabled(True)
        self.searchContent.setObjectName("searchContent")
        self.gridLayout_3.addWidget(self.searchContent, 0, 0, 1, 1)
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchButton.sizePolicy().hasHeightForWidth())
        self.searchButton.setSizePolicy(sizePolicy)
        self.searchButton.setObjectName("searchButton")
        self.gridLayout_3.addWidget(self.searchButton, 0, 1, 1, 1)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveButton.sizePolicy().hasHeightForWidth())
        self.saveButton.setSizePolicy(sizePolicy)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout_3.addWidget(self.saveButton, 0, 2, 1, 1)
        self.createBotton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createBotton.sizePolicy().hasHeightForWidth())
        self.createBotton.setSizePolicy(sizePolicy)
        self.createBotton.setObjectName("createBotton")
        self.gridLayout_3.addWidget(self.createBotton, 0, 3, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelButton.sizePolicy().hasHeightForWidth())
        self.cancelButton.setSizePolicy(sizePolicy)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout_3.addWidget(self.cancelButton, 0, 4, 1, 1)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_2.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget_2.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_2.setTabBarAutoHide(True)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.tabWidget = QtWidgets.QTabWidget(self.tab)
        self.tabWidget.setObjectName("tabWidget")
        self.companyTab = QtWidgets.QWidget()
        self.companyTab.setObjectName("companyTab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.companyTab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_3 = QtWidgets.QGroupBox(self.companyTab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.depStructLable = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depStructLable.sizePolicy().hasHeightForWidth())
        self.depStructLable.setSizePolicy(sizePolicy)
        self.depStructLable.setObjectName("depStructLable")
        self.gridLayout_10.addWidget(self.depStructLable, 0, 0, 1, 1)
        self.previewPic = QtWidgets.QListWidget(self.groupBox_3)
        self.previewPic.setObjectName("previewPic")
        self.gridLayout_10.addWidget(self.previewPic, 1, 0, 2, 1)
        self.previewButton = QtWidgets.QPushButton(self.groupBox_3)
        self.previewButton.setObjectName("previewButton")
        self.gridLayout_10.addWidget(self.previewButton, 2, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.borderLable = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.borderLable.sizePolicy().hasHeightForWidth())
        self.borderLable.setSizePolicy(sizePolicy)
        self.borderLable.setObjectName("borderLable")
        self.gridLayout_9.addWidget(self.borderLable, 0, 1, 1, 1)
        self.fontLable = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontLable.sizePolicy().hasHeightForWidth())
        self.fontLable.setSizePolicy(sizePolicy)
        self.fontLable.setObjectName("fontLable")
        self.gridLayout_9.addWidget(self.fontLable, 0, 2, 1, 1)
        self.level1Lable = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.level1Lable.sizePolicy().hasHeightForWidth())
        self.level1Lable.setSizePolicy(sizePolicy)
        self.level1Lable.setObjectName("level1Lable")
        self.gridLayout_9.addWidget(self.level1Lable, 1, 0, 1, 1)
        self.level1Border = QtWidgets.QPushButton(self.groupBox_2)
        self.level1Border.setMinimumSize(QtCore.QSize(20, 20))
        self.level1Border.setMaximumSize(QtCore.QSize(20, 20))
        self.level1Border.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.level1Border.setAutoFillBackground(False)
        self.level1Border.setStyleSheet("background-color:rgb(0, 128, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"gridline-color:rgb(0, 0, 0);")
        self.level1Border.setText("")
        self.level1Border.setObjectName("level1Border")
        self.gridLayout_9.addWidget(self.level1Border, 1, 1, 1, 1)
        self.level1Font = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.level1Font.sizePolicy().hasHeightForWidth())
        self.level1Font.setSizePolicy(sizePolicy)
        self.level1Font.setMinimumSize(QtCore.QSize(20, 20))
        self.level1Font.setMaximumSize(QtCore.QSize(20, 20))
        self.level1Font.setStyleSheet("background-color:rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"gridline-color:rgb(0, 0, 0);")
        self.level1Font.setText("")
        self.level1Font.setObjectName("level1Font")
        self.gridLayout_9.addWidget(self.level1Font, 1, 2, 1, 1)
        self.level1Width = QtWidgets.QSpinBox(self.groupBox_2)
        self.level1Width.setMinimumSize(QtCore.QSize(42, 20))
        self.level1Width.setMaximumSize(QtCore.QSize(42, 20))
        self.level1Width.setMinimum(1)
        self.level1Width.setProperty("value", 3)
        self.level1Width.setObjectName("level1Width")
        self.gridLayout_9.addWidget(self.level1Width, 1, 3, 1, 1)
        self.level2Lable = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.level2Lable.sizePolicy().hasHeightForWidth())
        self.level2Lable.setSizePolicy(sizePolicy)
        self.level2Lable.setObjectName("level2Lable")
        self.gridLayout_9.addWidget(self.level2Lable, 2, 0, 1, 1)
        self.level2Border = QtWidgets.QPushButton(self.groupBox_2)
        self.level2Border.setMinimumSize(QtCore.QSize(20, 20))
        self.level2Border.setMaximumSize(QtCore.QSize(20, 20))
        self.level2Border.setStyleSheet("background-color:rgb(128,0, 0);\n"
"border-color: rgb(0,0, 0);\n"
"gridline-color:rgb(0, 0, 0);")
        self.level2Border.setText("")
        self.level2Border.setObjectName("level2Border")
        self.gridLayout_9.addWidget(self.level2Border, 2, 1, 1, 1)
        self.level2Font = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.level2Font.sizePolicy().hasHeightForWidth())
        self.level2Font.setSizePolicy(sizePolicy)
        self.level2Font.setMinimumSize(QtCore.QSize(20, 20))
        self.level2Font.setMaximumSize(QtCore.QSize(20, 20))
        self.level2Font.setStyleSheet("background-color:rgb(0,0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"gridline-color:rgb(0, 0, 0);")
        self.level2Font.setText("")
        self.level2Font.setObjectName("level2Font")
        self.gridLayout_9.addWidget(self.level2Font, 2, 2, 1, 1)
        self.level2Width = QtWidgets.QSpinBox(self.groupBox_2)
        self.level2Width.setMinimumSize(QtCore.QSize(42, 20))
        self.level2Width.setMaximumSize(QtCore.QSize(42, 20))
        self.level2Width.setMinimum(1)
        self.level2Width.setProperty("value", 3)
        self.level2Width.setObjectName("level2Width")
        self.gridLayout_9.addWidget(self.level2Width, 2, 3, 1, 1)
        self.level3Lable = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.level3Lable.sizePolicy().hasHeightForWidth())
        self.level3Lable.setSizePolicy(sizePolicy)
        self.level3Lable.setObjectName("level3Lable")
        self.gridLayout_9.addWidget(self.level3Lable, 3, 0, 1, 1)
        self.level3Border = QtWidgets.QPushButton(self.groupBox_2)
        self.level3Border.setMinimumSize(QtCore.QSize(20, 20))
        self.level3Border.setMaximumSize(QtCore.QSize(20, 20))
        self.level3Border.setStyleSheet("background-color:rgb(0, 0, 128);\n"
"border-color: rgb(0, 0, 0);\n"
"gridline-color:rgb(0, 0, 0);")
        self.level3Border.setText("")
        self.level3Border.setObjectName("level3Border")
        self.gridLayout_9.addWidget(self.level3Border, 3, 1, 1, 1)
        self.level3Font = QtWidgets.QPushButton(self.groupBox_2)
        self.level3Font.setMinimumSize(QtCore.QSize(20, 20))
        self.level3Font.setMaximumSize(QtCore.QSize(20, 20))
        self.level3Font.setStyleSheet("background-color:rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"gridline-color:rgb(0, 0, 0);")
        self.level3Font.setText("")
        self.level3Font.setObjectName("level3Font")
        self.gridLayout_9.addWidget(self.level3Font, 3, 2, 1, 1)
        self.level3Width = QtWidgets.QSpinBox(self.groupBox_2)
        self.level3Width.setMinimumSize(QtCore.QSize(42, 20))
        self.level3Width.setMaximumSize(QtCore.QSize(42, 20))
        self.level3Width.setMinimum(1)
        self.level3Width.setProperty("value", 3)
        self.level3Width.setObjectName("level3Width")
        self.gridLayout_9.addWidget(self.level3Width, 3, 3, 1, 1)
        self.level4Lable = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.level4Lable.sizePolicy().hasHeightForWidth())
        self.level4Lable.setSizePolicy(sizePolicy)
        self.level4Lable.setObjectName("level4Lable")
        self.gridLayout_9.addWidget(self.level4Lable, 4, 0, 1, 1)
        self.level4Border = QtWidgets.QPushButton(self.groupBox_2)
        self.level4Border.setMinimumSize(QtCore.QSize(20, 20))
        self.level4Border.setMaximumSize(QtCore.QSize(20, 20))
        self.level4Border.setStyleSheet("background-color:rgb(255, 255, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"gridline-color:rgb(0, 0, 0);")
        self.level4Border.setText("")
        self.level4Border.setObjectName("level4Border")
        self.gridLayout_9.addWidget(self.level4Border, 4, 1, 1, 1)
        self.level4Font = QtWidgets.QPushButton(self.groupBox_2)
        self.level4Font.setMinimumSize(QtCore.QSize(20, 20))
        self.level4Font.setMaximumSize(QtCore.QSize(20, 20))
        self.level4Font.setStyleSheet("background-color:rgb(0,0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"gridline-color:rgb(0, 0, 0);")
        self.level4Font.setText("")
        self.level4Font.setObjectName("level4Font")
        self.gridLayout_9.addWidget(self.level4Font, 4, 2, 1, 1)
        self.level4Width = QtWidgets.QSpinBox(self.groupBox_2)
        self.level4Width.setMinimumSize(QtCore.QSize(42, 20))
        self.level4Width.setMaximumSize(QtCore.QSize(42, 20))
        self.level4Width.setMinimum(1)
        self.level4Width.setProperty("value", 3)
        self.level4Width.setObjectName("level4Width")
        self.gridLayout_9.addWidget(self.level4Width, 4, 3, 1, 1)
        self.heightLable = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heightLable.sizePolicy().hasHeightForWidth())
        self.heightLable.setSizePolicy(sizePolicy)
        self.heightLable.setObjectName("heightLable")
        self.gridLayout_9.addWidget(self.heightLable, 0, 3, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_2, 0, 1, 2, 1)
        self.gridLayout_7.addWidget(self.groupBox_3, 3, 2, 1, 1)
        self.fileInfo = QtWidgets.QGroupBox(self.companyTab)
        self.fileInfo.setObjectName("fileInfo")
        self.gridLayout = QtWidgets.QGridLayout(self.fileInfo)
        self.gridLayout.setObjectName("gridLayout")
        self.approverText = QtWidgets.QLineEdit(self.fileInfo)
        self.approverText.setObjectName("approverText")
        self.gridLayout.addWidget(self.approverText, 3, 4, 1, 1)
        self.approverLable = QtWidgets.QLabel(self.fileInfo)
        self.approverLable.setObjectName("approverLable")
        self.gridLayout.addWidget(self.approverLable, 3, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.fileInfo)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.corporateText = QtWidgets.QLineEdit(self.fileInfo)
        self.corporateText.setObjectName("corporateText")
        self.gridLayout.addWidget(self.corporateText, 0, 2, 1, 1)
        self.managerText = QtWidgets.QLineEdit(self.fileInfo)
        self.managerText.setObjectName("managerText")
        self.gridLayout.addWidget(self.managerText, 0, 4, 1, 1)
        self.managerLable = QtWidgets.QLabel(self.fileInfo)
        self.managerLable.setObjectName("managerLable")
        self.gridLayout.addWidget(self.managerLable, 0, 3, 1, 1)
        self.guandaiLable = QtWidgets.QLabel(self.fileInfo)
        self.guandaiLable.setObjectName("guandaiLable")
        self.gridLayout.addWidget(self.guandaiLable, 1, 1, 1, 1)
        self.guandaiText = QtWidgets.QLineEdit(self.fileInfo)
        self.guandaiText.setObjectName("guandaiText")
        self.gridLayout.addWidget(self.guandaiText, 1, 2, 1, 1)
        self.compilerText = QtWidgets.QLineEdit(self.fileInfo)
        self.compilerText.setObjectName("compilerText")
        self.gridLayout.addWidget(self.compilerText, 1, 4, 1, 1)
        self.compilerLable = QtWidgets.QLabel(self.fileInfo)
        self.compilerLable.setObjectName("compilerLable")
        self.gridLayout.addWidget(self.compilerLable, 1, 3, 1, 1)
        self.auditText = QtWidgets.QLineEdit(self.fileInfo)
        self.auditText.setObjectName("auditText")
        self.gridLayout.addWidget(self.auditText, 3, 2, 1, 1)
        self.auditLable = QtWidgets.QLabel(self.fileInfo)
        self.auditLable.setObjectName("auditLable")
        self.gridLayout.addWidget(self.auditLable, 3, 1, 1, 1)
        self.announcerLable = QtWidgets.QLabel(self.fileInfo)
        self.announcerLable.setObjectName("announcerLable")
        self.gridLayout.addWidget(self.announcerLable, 4, 1, 1, 1)
        self.announcerText = QtWidgets.QLineEdit(self.fileInfo)
        self.announcerText.setObjectName("announcerText")
        self.gridLayout.addWidget(self.announcerText, 4, 2, 1, 1)
        self.gridLayout_7.addWidget(self.fileInfo, 0, 2, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.companyTab)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.logoView = QtWidgets.QGraphicsView(self.groupBox_7)
        self.logoView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.logoView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.logoView.setObjectName("logoView")
        self.gridLayout_13.addWidget(self.logoView, 0, 0, 1, 1)
        self.logoChooseButton = QtWidgets.QToolButton(self.groupBox_7)
        self.logoChooseButton.setObjectName("logoChooseButton")
        self.gridLayout_13.addWidget(self.logoChooseButton, 1, 1, 1, 1)
        self.Logo = QtWidgets.QPlainTextEdit(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Logo.sizePolicy().hasHeightForWidth())
        self.Logo.setSizePolicy(sizePolicy)
        self.Logo.setMinimumSize(QtCore.QSize(0, 40))
        self.Logo.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Logo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Logo.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Logo.setUndoRedoEnabled(False)
        self.Logo.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.Logo.setReadOnly(False)
        self.Logo.setOverwriteMode(True)
        self.Logo.setTextInteractionFlags(QtCore.Qt.TextEditorInteraction)
        self.Logo.setBackgroundVisible(False)
        self.Logo.setObjectName("Logo")
        self.gridLayout_13.addWidget(self.Logo, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_7, 1, 2, 1, 1)
        self.basicInfo = QtWidgets.QGroupBox(self.companyTab)
        self.basicInfo.setObjectName("basicInfo")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.basicInfo)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.companyLable = QtWidgets.QLabel(self.basicInfo)
        self.companyLable.setObjectName("companyLable")
        self.gridLayout_2.addWidget(self.companyLable, 0, 0, 1, 1)
        self.fileNameLable = QtWidgets.QLabel(self.basicInfo)
        self.fileNameLable.setObjectName("fileNameLable")
        self.gridLayout_2.addWidget(self.fileNameLable, 1, 0, 1, 1)
        self.companyText = QtWidgets.QLineEdit(self.basicInfo)
        self.companyText.setObjectName("companyText")
        self.gridLayout_2.addWidget(self.companyText, 0, 3, 1, 1)
        self.introductionLable = QtWidgets.QLabel(self.basicInfo)
        self.introductionLable.setObjectName("introductionLable")
        self.gridLayout_2.addWidget(self.introductionLable, 8, 0, 1, 4)
        self.addressLable = QtWidgets.QLabel(self.basicInfo)
        self.addressLable.setObjectName("addressLable")
        self.gridLayout_2.addWidget(self.addressLable, 2, 0, 1, 1)
        self.introductionText = QtWidgets.QPlainTextEdit(self.basicInfo)
        self.introductionText.setTabChangesFocus(True)
        self.introductionText.setObjectName("introductionText")
        self.gridLayout_2.addWidget(self.introductionText, 9, 0, 1, 4)
        self.coverFieldText = QtWidgets.QLineEdit(self.basicInfo)
        self.coverFieldText.setObjectName("coverFieldText")
        self.gridLayout_2.addWidget(self.coverFieldText, 3, 3, 1, 1)
        self.coverFieldLable = QtWidgets.QLabel(self.basicInfo)
        self.coverFieldLable.setObjectName("coverFieldLable")
        self.gridLayout_2.addWidget(self.coverFieldLable, 3, 0, 1, 1)
        self.policyText = QtWidgets.QLineEdit(self.basicInfo)
        self.policyText.setObjectName("policyText")
        self.gridLayout_2.addWidget(self.policyText, 4, 3, 1, 1)
        self.policyLable = QtWidgets.QLabel(self.basicInfo)
        self.policyLable.setObjectName("policyLable")
        self.gridLayout_2.addWidget(self.policyLable, 4, 0, 1, 1)
        self.fileNameText = QtWidgets.QLineEdit(self.basicInfo)
        self.fileNameText.setObjectName("fileNameText")
        self.gridLayout_2.addWidget(self.fileNameText, 1, 3, 1, 1)
        self.addressText = QtWidgets.QLineEdit(self.basicInfo)
        self.addressText.setObjectName("addressText")
        self.gridLayout_2.addWidget(self.addressText, 2, 3, 1, 1)
        self.zipLable = QtWidgets.QLabel(self.basicInfo)
        self.zipLable.setObjectName("zipLable")
        self.gridLayout_2.addWidget(self.zipLable, 6, 0, 1, 1)
        self.phoneLable = QtWidgets.QLabel(self.basicInfo)
        self.phoneLable.setObjectName("phoneLable")
        self.gridLayout_2.addWidget(self.phoneLable, 7, 0, 1, 1)
        self.zipText = QtWidgets.QLineEdit(self.basicInfo)
        self.zipText.setObjectName("zipText")
        self.gridLayout_2.addWidget(self.zipText, 6, 3, 1, 1)
        self.phoneText = QtWidgets.QLineEdit(self.basicInfo)
        self.phoneText.setObjectName("phoneText")
        self.gridLayout_2.addWidget(self.phoneText, 7, 3, 1, 1)
        self.gridLayout_7.addWidget(self.basicInfo, 0, 1, 4, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.companyTab)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.auditDateLable = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.auditDateLable.sizePolicy().hasHeightForWidth())
        self.auditDateLable.setSizePolicy(sizePolicy)
        self.auditDateLable.setObjectName("auditDateLable")
        self.gridLayout_12.addWidget(self.auditDateLable, 0, 0, 1, 1)
        self.auditDateText = QtWidgets.QDateEdit(self.groupBox_6)
        self.auditDateText.setObjectName("auditDateText")
        self.gridLayout_12.addWidget(self.auditDateText, 0, 1, 1, 1)
        self.releaseDateLable = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.releaseDateLable.sizePolicy().hasHeightForWidth())
        self.releaseDateLable.setSizePolicy(sizePolicy)
        self.releaseDateLable.setObjectName("releaseDateLable")
        self.gridLayout_12.addWidget(self.releaseDateLable, 0, 2, 1, 1)
        self.releaseDateText = QtWidgets.QDateEdit(self.groupBox_6)
        self.releaseDateText.setObjectName("releaseDateText")
        self.gridLayout_12.addWidget(self.releaseDateText, 0, 3, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_6, 2, 2, 1, 1)
        self.tabWidget.addTab(self.companyTab, "")
        self.departmentTab = QtWidgets.QWidget()
        self.departmentTab.setObjectName("departmentTab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.departmentTab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox_4 = QtWidgets.QGroupBox(self.departmentTab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.AddDep = QtWidgets.QPushButton(self.groupBox_4)
        self.AddDep.setObjectName("AddDep")
        self.gridLayout_4.addWidget(self.AddDep, 1, 0, 1, 1)
        self.DeleteDep = QtWidgets.QPushButton(self.groupBox_4)
        self.DeleteDep.setObjectName("DeleteDep")
        self.gridLayout_4.addWidget(self.DeleteDep, 1, 1, 1, 1)
        self.departmentList = QtWidgets.QListWidget(self.groupBox_4)
        self.departmentList.setObjectName("departmentList")
        self.gridLayout_4.addWidget(self.departmentList, 0, 0, 1, 2)
        self.gridLayout_8.addWidget(self.groupBox_4, 0, 0, 3, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.departmentTab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_27 = QtWidgets.QLabel(self.groupBox_5)
        self.label_27.setObjectName("label_27")
        self.gridLayout_5.addWidget(self.label_27, 1, 0, 1, 1)
        self.depIntro = QtWidgets.QPlainTextEdit(self.groupBox_5)
        self.depIntro.setTabChangesFocus(True)
        self.depIntro.setObjectName("depIntro")
        self.gridLayout_5.addWidget(self.depIntro, 2, 0, 1, 4)
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 1)
        self.depName = QtWidgets.QLineEdit(self.groupBox_5)
        self.depName.setObjectName("depName")
        self.gridLayout_5.addWidget(self.depName, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 2, 1, 1)
        self.depLevel = QtWidgets.QSpinBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.depLevel.sizePolicy().hasHeightForWidth())
        self.depLevel.setSizePolicy(sizePolicy)
        self.depLevel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.depLevel.setMinimum(1)
        self.depLevel.setMaximum(4)
        self.depLevel.setObjectName("depLevel")
        self.gridLayout_5.addWidget(self.depLevel, 0, 3, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_5, 0, 1, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(self.departmentTab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.duty_5 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_5.setObjectName("duty_5")
        self.gridLayout_6.addWidget(self.duty_5, 8, 0, 1, 1)
        self.duty_14 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_14.setObjectName("duty_14")
        self.gridLayout_6.addWidget(self.duty_14, 8, 1, 1, 1)
        self.duty_7 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_7.setObjectName("duty_7")
        self.gridLayout_6.addWidget(self.duty_7, 10, 0, 1, 1)
        self.duty_18 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_18.setObjectName("duty_18")
        self.gridLayout_6.addWidget(self.duty_18, 12, 1, 1, 1)
        self.duty_23 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_23.setObjectName("duty_23")
        self.gridLayout_6.addWidget(self.duty_23, 8, 2, 1, 1)
        self.duty_6 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_6.setObjectName("duty_6")
        self.gridLayout_6.addWidget(self.duty_6, 9, 0, 1, 1)
        self.duty_24 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_24.setObjectName("duty_24")
        self.gridLayout_6.addWidget(self.duty_24, 9, 2, 1, 1)
        self.duty_17 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_17.setObjectName("duty_17")
        self.gridLayout_6.addWidget(self.duty_17, 11, 1, 1, 1)
        self.duty_9 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_9.setObjectName("duty_9")
        self.gridLayout_6.addWidget(self.duty_9, 12, 0, 1, 1)
        self.duty_8 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_8.setObjectName("duty_8")
        self.gridLayout_6.addWidget(self.duty_8, 11, 0, 1, 1)
        self.duty_20 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_20.setObjectName("duty_20")
        self.gridLayout_6.addWidget(self.duty_20, 3, 2, 1, 1)
        self.duty_25 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_25.setObjectName("duty_25")
        self.gridLayout_6.addWidget(self.duty_25, 10, 2, 1, 1)
        self.duty_26 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_26.setObjectName("duty_26")
        self.gridLayout_6.addWidget(self.duty_26, 11, 2, 1, 1)
        self.duty_21 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_21.setObjectName("duty_21")
        self.gridLayout_6.addWidget(self.duty_21, 5, 2, 1, 1)
        self.duty_13 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_13.setObjectName("duty_13")
        self.gridLayout_6.addWidget(self.duty_13, 7, 1, 1, 1)
        self.duty_15 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_15.setObjectName("duty_15")
        self.gridLayout_6.addWidget(self.duty_15, 9, 1, 1, 1)
        self.duty_4 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_4.setObjectName("duty_4")
        self.gridLayout_6.addWidget(self.duty_4, 7, 0, 1, 1)
        self.duty_27 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_27.setObjectName("duty_27")
        self.gridLayout_6.addWidget(self.duty_27, 12, 2, 1, 1)
        self.duty_22 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_22.setObjectName("duty_22")
        self.gridLayout_6.addWidget(self.duty_22, 7, 2, 1, 1)
        self.duty_16 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_16.setObjectName("duty_16")
        self.gridLayout_6.addWidget(self.duty_16, 10, 1, 1, 1)
        self.duty_1 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_1.setChecked(False)
        self.duty_1.setObjectName("duty_1")
        self.gridLayout_6.addWidget(self.duty_1, 0, 0, 1, 1)
        self.duty_10 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_10.setObjectName("duty_10")
        self.gridLayout_6.addWidget(self.duty_10, 0, 1, 1, 1)
        self.duty_11 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_11.setObjectName("duty_11")
        self.gridLayout_6.addWidget(self.duty_11, 2, 1, 3, 1)
        self.duty_2 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_2.setObjectName("duty_2")
        self.gridLayout_6.addWidget(self.duty_2, 2, 0, 3, 1)
        self.duty_3 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_3.setObjectName("duty_3")
        self.gridLayout_6.addWidget(self.duty_3, 5, 0, 2, 1)
        self.duty_12 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_12.setObjectName("duty_12")
        self.gridLayout_6.addWidget(self.duty_12, 5, 1, 2, 1)
        self.duty_28 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_28.setObjectName("duty_28")
        self.gridLayout_6.addWidget(self.duty_28, 0, 3, 1, 1)
        self.duty_29 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_29.setObjectName("duty_29")
        self.gridLayout_6.addWidget(self.duty_29, 3, 3, 1, 1)
        self.duty_30 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_30.setObjectName("duty_30")
        self.gridLayout_6.addWidget(self.duty_30, 5, 3, 1, 1)
        self.duty_31 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_31.setObjectName("duty_31")
        self.gridLayout_6.addWidget(self.duty_31, 7, 3, 1, 1)
        self.duty_32 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_32.setObjectName("duty_32")
        self.gridLayout_6.addWidget(self.duty_32, 8, 3, 1, 1)
        self.duty_33 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_33.setObjectName("duty_33")
        self.gridLayout_6.addWidget(self.duty_33, 9, 3, 1, 1)
        self.duty_34 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_34.setObjectName("duty_34")
        self.gridLayout_6.addWidget(self.duty_34, 10, 3, 1, 1)
        self.duty_35 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_35.setObjectName("duty_35")
        self.gridLayout_6.addWidget(self.duty_35, 11, 3, 1, 1)
        self.duty_36 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_36.setObjectName("duty_36")
        self.gridLayout_6.addWidget(self.duty_36, 12, 3, 1, 1)
        self.duty_37 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_37.setObjectName("duty_37")
        self.gridLayout_6.addWidget(self.duty_37, 0, 4, 1, 1)
        self.duty_38 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_38.setObjectName("duty_38")
        self.gridLayout_6.addWidget(self.duty_38, 3, 4, 1, 1)
        self.duty_39 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_39.setObjectName("duty_39")
        self.gridLayout_6.addWidget(self.duty_39, 5, 4, 1, 1)
        self.duty_40 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_40.setObjectName("duty_40")
        self.gridLayout_6.addWidget(self.duty_40, 7, 4, 1, 1)
        self.duty_41 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_41.setObjectName("duty_41")
        self.gridLayout_6.addWidget(self.duty_41, 8, 4, 1, 1)
        self.duty_42 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_42.setObjectName("duty_42")
        self.gridLayout_6.addWidget(self.duty_42, 9, 4, 1, 1)
        self.duty_19 = QtWidgets.QCheckBox(self.groupBox)
        self.duty_19.setObjectName("duty_19")
        self.gridLayout_6.addWidget(self.duty_19, 0, 2, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox, 1, 1, 1, 2)
        self.addOrModifyDep = QtWidgets.QPushButton(self.departmentTab)
        self.addOrModifyDep.setObjectName("addOrModifyDep")
        self.gridLayout_8.addWidget(self.addOrModifyDep, 2, 1, 1, 1)
        self.cancelDep = QtWidgets.QPushButton(self.departmentTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelDep.sizePolicy().hasHeightForWidth())
        self.cancelDep.setSizePolicy(sizePolicy)
        self.cancelDep.setObjectName("cancelDep")
        self.gridLayout_8.addWidget(self.cancelDep, 2, 2, 1, 1)
        self.tabWidget.addTab(self.departmentTab, "")
        self.gridLayout_11.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.gridLayout_3.addWidget(self.tabWidget_2, 1, 0, 1, 5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actioncaidan = QtWidgets.QAction(MainWindow)
        self.actioncaidan.setObjectName("actioncaidan")
        self.actionsetting = QtWidgets.QAction(MainWindow)
        self.actionsetting.setObjectName("actionsetting")
        self.actioncaocun = QtWidgets.QAction(MainWindow)
        self.actioncaocun.setObjectName("actioncaocun")
        self.actionmuban = QtWidgets.QAction(MainWindow)
        self.actionmuban.setObjectName("actionmuban")
        self.actiontuichu = QtWidgets.QAction(MainWindow)
        self.actiontuichu.setObjectName("actiontuichu")
        self.actionbaocunlujing = QtWidgets.QAction(MainWindow)
        self.actionbaocunlujing.setObjectName("actionbaocunlujing")
        self.actiontuichu_2 = QtWidgets.QAction(MainWindow)
        self.actiontuichu_2.setObjectName("actiontuichu_2")

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.searchContent, self.searchButton)
        MainWindow.setTabOrder(self.searchButton, self.companyText)
        MainWindow.setTabOrder(self.companyText, self.fileNameText)
        MainWindow.setTabOrder(self.fileNameText, self.addressText)
        MainWindow.setTabOrder(self.addressText, self.coverFieldText)
        MainWindow.setTabOrder(self.coverFieldText, self.policyText)
        MainWindow.setTabOrder(self.policyText, self.introductionText)
        MainWindow.setTabOrder(self.introductionText, self.approverText)
        MainWindow.setTabOrder(self.approverText, self.level1Border)
        MainWindow.setTabOrder(self.level1Border, self.level1Font)
        MainWindow.setTabOrder(self.level1Font, self.level1Width)
        MainWindow.setTabOrder(self.level1Width, self.level2Border)
        MainWindow.setTabOrder(self.level2Border, self.level2Font)
        MainWindow.setTabOrder(self.level2Font, self.level2Width)
        MainWindow.setTabOrder(self.level2Width, self.level3Border)
        MainWindow.setTabOrder(self.level3Border, self.level3Font)
        MainWindow.setTabOrder(self.level3Font, self.level3Width)
        MainWindow.setTabOrder(self.level3Width, self.level4Border)
        MainWindow.setTabOrder(self.level4Border, self.level4Font)
        MainWindow.setTabOrder(self.level4Font, self.level4Width)
        MainWindow.setTabOrder(self.level4Width, self.previewButton)
        MainWindow.setTabOrder(self.previewButton, self.previewPic)
        MainWindow.setTabOrder(self.previewPic, self.AddDep)
        MainWindow.setTabOrder(self.AddDep, self.DeleteDep)
        MainWindow.setTabOrder(self.DeleteDep, self.departmentList)
        MainWindow.setTabOrder(self.departmentList, self.depName)
        MainWindow.setTabOrder(self.depName, self.depLevel)
        MainWindow.setTabOrder(self.depLevel, self.depIntro)
        MainWindow.setTabOrder(self.depIntro, self.duty_1)
        MainWindow.setTabOrder(self.duty_1, self.duty_2)
        MainWindow.setTabOrder(self.duty_2, self.duty_3)
        MainWindow.setTabOrder(self.duty_3, self.duty_4)
        MainWindow.setTabOrder(self.duty_4, self.duty_5)
        MainWindow.setTabOrder(self.duty_5, self.duty_6)
        MainWindow.setTabOrder(self.duty_6, self.duty_7)
        MainWindow.setTabOrder(self.duty_7, self.duty_8)
        MainWindow.setTabOrder(self.duty_8, self.duty_9)
        MainWindow.setTabOrder(self.duty_9, self.duty_10)
        MainWindow.setTabOrder(self.duty_10, self.duty_11)
        MainWindow.setTabOrder(self.duty_11, self.duty_12)
        MainWindow.setTabOrder(self.duty_12, self.duty_13)
        MainWindow.setTabOrder(self.duty_13, self.duty_14)
        MainWindow.setTabOrder(self.duty_14, self.duty_15)
        MainWindow.setTabOrder(self.duty_15, self.duty_16)
        MainWindow.setTabOrder(self.duty_16, self.duty_17)
        MainWindow.setTabOrder(self.duty_17, self.duty_18)
        MainWindow.setTabOrder(self.duty_18, self.duty_19)
        MainWindow.setTabOrder(self.duty_19, self.duty_20)
        MainWindow.setTabOrder(self.duty_20, self.duty_21)
        MainWindow.setTabOrder(self.duty_21, self.duty_22)
        MainWindow.setTabOrder(self.duty_22, self.duty_23)
        MainWindow.setTabOrder(self.duty_23, self.duty_24)
        MainWindow.setTabOrder(self.duty_24, self.duty_25)
        MainWindow.setTabOrder(self.duty_25, self.duty_26)
        MainWindow.setTabOrder(self.duty_26, self.duty_27)
        MainWindow.setTabOrder(self.duty_27, self.duty_28)
        MainWindow.setTabOrder(self.duty_28, self.duty_29)
        MainWindow.setTabOrder(self.duty_29, self.duty_30)
        MainWindow.setTabOrder(self.duty_30, self.duty_31)
        MainWindow.setTabOrder(self.duty_31, self.duty_32)
        MainWindow.setTabOrder(self.duty_32, self.duty_33)
        MainWindow.setTabOrder(self.duty_33, self.duty_34)
        MainWindow.setTabOrder(self.duty_34, self.duty_35)
        MainWindow.setTabOrder(self.duty_35, self.duty_36)
        MainWindow.setTabOrder(self.duty_36, self.duty_37)
        MainWindow.setTabOrder(self.duty_37, self.duty_38)
        MainWindow.setTabOrder(self.duty_38, self.duty_39)
        MainWindow.setTabOrder(self.duty_39, self.duty_40)
        MainWindow.setTabOrder(self.duty_40, self.duty_41)
        MainWindow.setTabOrder(self.duty_41, self.duty_42)
        MainWindow.setTabOrder(self.duty_42, self.addOrModifyDep)
        MainWindow.setTabOrder(self.addOrModifyDep, self.cancelDep)
        MainWindow.setTabOrder(self.cancelDep, self.createBotton)
        MainWindow.setTabOrder(self.createBotton, self.cancelButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "文档生成器v1.0"))
        self.searchButton.setText(_translate("MainWindow", "搜索"))
        self.saveButton.setText(_translate("MainWindow", "保存"))
        self.createBotton.setText(_translate("MainWindow", "文档生成"))
        self.cancelButton.setText(_translate("MainWindow", "放弃修改"))
        self.groupBox_3.setTitle(_translate("MainWindow", "部门结构图"))
        self.depStructLable.setText(_translate("MainWindow", "部门结构"))
        self.previewButton.setText(_translate("MainWindow", "预览图片"))
        self.groupBox_2.setTitle(_translate("MainWindow", "样式"))
        self.borderLable.setText(_translate("MainWindow", "边框"))
        self.fontLable.setText(_translate("MainWindow", "字体"))
        self.level1Lable.setText(_translate("MainWindow", "第一层"))
        self.level2Lable.setText(_translate("MainWindow", "第二层"))
        self.level3Lable.setText(_translate("MainWindow", "第三层"))
        self.level4Lable.setText(_translate("MainWindow", "第四层"))
        self.heightLable.setText(_translate("MainWindow", "行宽"))
        self.fileInfo.setTitle(_translate("MainWindow", "公司（组织级人员）信息"))
        self.approverLable.setText(_translate("MainWindow", "批准人"))
        self.label_3.setText(_translate("MainWindow", "法人代表"))
        self.managerLable.setText(_translate("MainWindow", "总经理"))
        self.guandaiLable.setText(_translate("MainWindow", "管理者代表"))
        self.compilerLable.setText(_translate("MainWindow", "编制人"))
        self.auditLable.setText(_translate("MainWindow", "审核人"))
        self.announcerLable.setText(_translate("MainWindow", "发布人"))
        self.groupBox_7.setTitle(_translate("MainWindow", "公司图标"))
        self.logoChooseButton.setText(_translate("MainWindow", "..."))
        self.Logo.setPlaceholderText(_translate("MainWindow", "请将公司图标拖拽至此或点击右边的选择按钮"))
        self.basicInfo.setTitle(_translate("MainWindow", "公司基础信息"))
        self.companyLable.setText(_translate("MainWindow", "公司名称"))
        self.fileNameLable.setText(_translate("MainWindow", "公司缩写"))
        self.introductionLable.setText(_translate("MainWindow", "公司简介"))
        self.addressLable.setText(_translate("MainWindow", "通信地址"))
        self.coverFieldLable.setText(_translate("MainWindow", "覆盖范围"))
        self.policyLable.setText(_translate("MainWindow", "服务方针"))
        self.zipLable.setText(_translate("MainWindow", "公司邮编"))
        self.phoneLable.setText(_translate("MainWindow", "公司电话"))
        self.groupBox_6.setTitle(_translate("MainWindow", "文档日期输入"))
        self.auditDateLable.setText(_translate("MainWindow", "编制日期"))
        self.auditDateText.setDisplayFormat(_translate("MainWindow", "yyyy年MM月dd日"))
        self.releaseDateLable.setText(_translate("MainWindow", "实施日期"))
        self.releaseDateText.setDisplayFormat(_translate("MainWindow", "yyyy年MM月dd日"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.companyTab), _translate("MainWindow", "公司信息"))
        self.groupBox_4.setTitle(_translate("MainWindow", "部门列表"))
        self.AddDep.setText(_translate("MainWindow", "添加"))
        self.DeleteDep.setText(_translate("MainWindow", "删除"))
        self.groupBox_5.setTitle(_translate("MainWindow", "部门信息"))
        self.label_27.setText(_translate("MainWindow", "部门简介"))
        self.label_2.setText(_translate("MainWindow", "部门名称"))
        self.label.setText(_translate("MainWindow", "部门级别"))
        self.groupBox.setTitle(_translate("MainWindow", "部门职责"))
        self.duty_5.setText(_translate("MainWindow", "4.1.3 权限、职\n"
"责和沟通"))
        self.duty_14.setText(_translate("MainWindow", "4.4.2 人力资源"))
        self.duty_7.setText(_translate("MainWindow", "4.2 治理由其他方\n"
"运行的过程"))
        self.duty_18.setText(_translate("MainWindow", "4.5.3 实施和运\n"
"行服务管理体系\n"
"（Do）"))
        self.duty_23.setText(_translate("MainWindow", "4.5.5 维护和改进\n"
"服务管理体系\n"
"（Act）"))
        self.duty_6.setText(_translate("MainWindow", "4.1.4 管理者代\n"
"表"))
        self.duty_24.setText(_translate("MainWindow", "4.5.5.1 总要求"))
        self.duty_17.setText(_translate("MainWindow", "4.5.2 策划服务\n"
"管理体系（Plan）"))
        self.duty_9.setText(_translate("MainWindow", "4.3.1 文件的建立\n"
"和维护"))
        self.duty_8.setText(_translate("MainWindow", "4.3 文件管理"))
        self.duty_20.setText(_translate("MainWindow", "4.5.4.1 总要求"))
        self.duty_25.setText(_translate("MainWindow", "4.5.5.2 管理改进"))
        self.duty_26.setText(_translate("MainWindow", "5.1 总要求"))
        self.duty_21.setText(_translate("MainWindow", "4.5.4.2 内部审\n"
"核"))
        self.duty_13.setText(_translate("MainWindow", "4.4.1 资源提供"))
        self.duty_15.setText(_translate("MainWindow", "4.5 建立和改进\n"
"服务管理体系\n"
"（SMS）"))
        self.duty_4.setText(_translate("MainWindow", "4.1.2 服务管理方\n"
"针"))
        self.duty_27.setText(_translate("MainWindow", "5.2 策划新的或变\n"
"更的服务"))
        self.duty_22.setText(_translate("MainWindow", "4.5.4.3 管理评审"))
        self.duty_16.setText(_translate("MainWindow", "4.5.1 定义范围"))
        self.duty_1.setText(_translate("MainWindow", "4 管理体系要求"))
        self.duty_10.setText(_translate("MainWindow", "4.3.2 文件控制"))
        self.duty_11.setText(_translate("MainWindow", "4.3.3 记录控制"))
        self.duty_2.setText(_translate("MainWindow", "4.1 管理职责"))
        self.duty_3.setText(_translate("MainWindow", "4.1.1 管理承诺"))
        self.duty_12.setText(_translate("MainWindow", "4.4 资源管理"))
        self.duty_28.setText(_translate("MainWindow", "5.3 设计和开发新\n"
"的或变更的服务"))
        self.duty_29.setText(_translate("MainWindow", "5.4 新的或变更的\n"
"服务转换"))
        self.duty_30.setText(_translate("MainWindow", "6.1 服务级别管理"))
        self.duty_31.setText(_translate("MainWindow", "6.2 服务报告管\n"
"理"))
        self.duty_32.setText(_translate("MainWindow", "6.3 服务的连续性\n"
"可用性管理"))
        self.duty_33.setText(_translate("MainWindow", "6.4 服务的预算和\n"
"核算"))
        self.duty_34.setText(_translate("MainWindow", "6.5 能力管理"))
        self.duty_35.setText(_translate("MainWindow", "6.6 信息安全"))
        self.duty_36.setText(_translate("MainWindow", "7.1 业务关系管理"))
        self.duty_37.setText(_translate("MainWindow", "7.2 供应商管理"))
        self.duty_38.setText(_translate("MainWindow", "8.1 事件和服务请\n"
"求管理"))
        self.duty_39.setText(_translate("MainWindow", "8.2 问题管理"))
        self.duty_40.setText(_translate("MainWindow", "9.1 配置管理"))
        self.duty_41.setText(_translate("MainWindow", "9.2 变更管理"))
        self.duty_42.setText(_translate("MainWindow", "9.3 发布和部署管\n"
"理"))
        self.duty_19.setText(_translate("MainWindow", "4.5.4 监视和评\n"
"审服务管理体系\n"
"（Check）"))
        self.addOrModifyDep.setText(_translate("MainWindow", "保存修改"))
        self.cancelDep.setText(_translate("MainWindow", "放弃修改"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.departmentTab), _translate("MainWindow", "部门信息"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "一层文件"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "二层文件"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "三层文件"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "四层文件"))
        self.actioncaidan.setText(_translate("MainWindow", "数据库配置"))
        self.actionsetting.setText(_translate("MainWindow", "setting"))
        self.actioncaocun.setText(_translate("MainWindow", "caocun"))
        self.actionmuban.setText(_translate("MainWindow", "模板选择"))
        self.actiontuichu.setText(_translate("MainWindow", "tuichu"))
        self.actionbaocunlujing.setText(_translate("MainWindow", "保存路径"))
        self.actiontuichu_2.setText(_translate("MainWindow", "退出"))

