# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1013, 757)
        MainWindow.setMinimumSize(QtCore.QSize(1013, 757))
        MainWindow.setMaximumSize(QtCore.QSize(1013, 757))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 30, 971, 681))
        self.tabWidget.setObjectName("tabWidget")
        self.companyTab = QtWidgets.QWidget()
        self.companyTab.setObjectName("companyTab")
        self.basicInfo = QtWidgets.QGroupBox(self.companyTab)
        self.basicInfo.setGeometry(QtCore.QRect(10, 10, 431, 641))
        self.basicInfo.setObjectName("basicInfo")
        self.introductionText = QtWidgets.QPlainTextEdit(self.basicInfo)
        self.introductionText.setGeometry(QtCore.QRect(40, 260, 361, 361))
        self.introductionText.setObjectName("introductionText")
        self.coverFieldText = QtWidgets.QLineEdit(self.basicInfo)
        self.coverFieldText.setGeometry(QtCore.QRect(110, 150, 291, 20))
        self.coverFieldText.setObjectName("coverFieldText")
        self.coverFieldLable = QtWidgets.QLabel(self.basicInfo)
        self.coverFieldLable.setGeometry(QtCore.QRect(40, 150, 61, 20))
        self.coverFieldLable.setObjectName("coverFieldLable")
        self.fileNameLable = QtWidgets.QLabel(self.basicInfo)
        self.fileNameLable.setGeometry(QtCore.QRect(40, 60, 54, 12))
        self.fileNameLable.setObjectName("fileNameLable")
        self.fileNameText = QtWidgets.QLineEdit(self.basicInfo)
        self.fileNameText.setGeometry(QtCore.QRect(110, 60, 291, 20))
        self.fileNameText.setObjectName("fileNameText")
        self.companyLable = QtWidgets.QLabel(self.basicInfo)
        self.companyLable.setGeometry(QtCore.QRect(40, 20, 54, 12))
        self.companyLable.setObjectName("companyLable")
        self.companyText = QtWidgets.QLineEdit(self.basicInfo)
        self.companyText.setGeometry(QtCore.QRect(110, 20, 291, 20))
        self.companyText.setObjectName("companyText")
        self.addressLable = QtWidgets.QLabel(self.basicInfo)
        self.addressLable.setGeometry(QtCore.QRect(40, 110, 54, 12))
        self.addressLable.setObjectName("addressLable")
        self.addressText = QtWidgets.QLineEdit(self.basicInfo)
        self.addressText.setGeometry(QtCore.QRect(110, 110, 291, 20))
        self.addressText.setObjectName("addressText")
        self.introductionLable = QtWidgets.QLabel(self.basicInfo)
        self.introductionLable.setGeometry(QtCore.QRect(40, 230, 81, 16))
        self.introductionLable.setObjectName("introductionLable")
        self.policyText = QtWidgets.QLineEdit(self.basicInfo)
        self.policyText.setGeometry(QtCore.QRect(110, 200, 291, 20))
        self.policyText.setObjectName("policyText")
        self.policyLable = QtWidgets.QLabel(self.basicInfo)
        self.policyLable.setGeometry(QtCore.QRect(40, 200, 54, 12))
        self.policyLable.setObjectName("policyLable")
        self.fileInfo = QtWidgets.QGroupBox(self.companyTab)
        self.fileInfo.setGeometry(QtCore.QRect(490, 10, 461, 641))
        self.fileInfo.setObjectName("fileInfo")
        self.auditDateText = QtWidgets.QDateEdit(self.fileInfo)
        self.auditDateText.setGeometry(QtCore.QRect(310, 240, 110, 22))
        self.auditDateText.setObjectName("auditDateText")
        self.zipText = QtWidgets.QLineEdit(self.fileInfo)
        self.zipText.setGeometry(QtCore.QRect(80, 190, 113, 20))
        self.zipText.setObjectName("zipText")
        self.approverText = QtWidgets.QLineEdit(self.fileInfo)
        self.approverText.setGeometry(QtCore.QRect(310, 90, 113, 20))
        self.approverText.setObjectName("approverText")
        self.announcerText = QtWidgets.QLineEdit(self.fileInfo)
        self.announcerText.setGeometry(QtCore.QRect(310, 140, 113, 20))
        self.announcerText.setObjectName("announcerText")
        self.employeesText = QtWidgets.QLineEdit(self.fileInfo)
        self.employeesText.setGeometry(QtCore.QRect(80, 90, 113, 20))
        self.employeesText.setObjectName("employeesText")
        self.managerText = QtWidgets.QLineEdit(self.fileInfo)
        self.managerText.setGeometry(QtCore.QRect(80, 40, 113, 20))
        self.managerText.setObjectName("managerText")
        self.releaseDateText = QtWidgets.QDateEdit(self.fileInfo)
        self.releaseDateText.setGeometry(QtCore.QRect(90, 240, 110, 22))
        self.releaseDateText.setObjectName("releaseDateText")
        self.phoneText = QtWidgets.QLineEdit(self.fileInfo)
        self.phoneText.setGeometry(QtCore.QRect(310, 190, 113, 20))
        self.phoneText.setObjectName("phoneText")
        self.guandaiText = QtWidgets.QLineEdit(self.fileInfo)
        self.guandaiText.setGeometry(QtCore.QRect(310, 40, 113, 20))
        self.guandaiText.setObjectName("guandaiText")
        self.auditText = QtWidgets.QLineEdit(self.fileInfo)
        self.auditText.setGeometry(QtCore.QRect(80, 140, 113, 20))
        self.auditText.setObjectName("auditText")
        self.managerLable = QtWidgets.QLabel(self.fileInfo)
        self.managerLable.setGeometry(QtCore.QRect(20, 40, 54, 12))
        self.managerLable.setObjectName("managerLable")
        self.guandaiLable = QtWidgets.QLabel(self.fileInfo)
        self.guandaiLable.setGeometry(QtCore.QRect(233, 40, 61, 20))
        self.guandaiLable.setObjectName("guandaiLable")
        self.employeesLable = QtWidgets.QLabel(self.fileInfo)
        self.employeesLable.setGeometry(QtCore.QRect(20, 90, 54, 12))
        self.employeesLable.setObjectName("employeesLable")
        self.approverLable = QtWidgets.QLabel(self.fileInfo)
        self.approverLable.setGeometry(QtCore.QRect(240, 90, 54, 12))
        self.approverLable.setObjectName("approverLable")
        self.auditLable = QtWidgets.QLabel(self.fileInfo)
        self.auditLable.setGeometry(QtCore.QRect(20, 140, 54, 12))
        self.auditLable.setObjectName("auditLable")
        self.announcerLable = QtWidgets.QLabel(self.fileInfo)
        self.announcerLable.setGeometry(QtCore.QRect(240, 140, 54, 12))
        self.announcerLable.setObjectName("announcerLable")
        self.zipLable = QtWidgets.QLabel(self.fileInfo)
        self.zipLable.setGeometry(QtCore.QRect(20, 190, 54, 12))
        self.zipLable.setObjectName("zipLable")
        self.phoneLable = QtWidgets.QLabel(self.fileInfo)
        self.phoneLable.setGeometry(QtCore.QRect(240, 190, 54, 12))
        self.phoneLable.setObjectName("phoneLable")
        self.releaseDateLable = QtWidgets.QLabel(self.fileInfo)
        self.releaseDateLable.setGeometry(QtCore.QRect(10, 240, 81, 16))
        self.releaseDateLable.setObjectName("releaseDateLable")
        self.auditDateLable = QtWidgets.QLabel(self.fileInfo)
        self.auditDateLable.setGeometry(QtCore.QRect(240, 240, 54, 12))
        self.auditDateLable.setObjectName("auditDateLable")
        self.groupBox_3 = QtWidgets.QGroupBox(self.fileInfo)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 340, 441, 291))
        self.groupBox_3.setObjectName("groupBox_3")
        self.depStructLable = QtWidgets.QLabel(self.groupBox_3)
        self.depStructLable.setGeometry(QtCore.QRect(10, 20, 54, 12))
        self.depStructLable.setObjectName("depStructLable")
        self.previewButton = QtWidgets.QPushButton(self.groupBox_3)
        self.previewButton.setGeometry(QtCore.QRect(360, 240, 75, 23))
        self.previewButton.setObjectName("previewButton")
        self.deSytle = QtWidgets.QLabel(self.groupBox_3)
        self.deSytle.setGeometry(QtCore.QRect(240, 20, 31, 16))
        self.deSytle.setObjectName("deSytle")
        self.level1Lable = QtWidgets.QLabel(self.groupBox_3)
        self.level1Lable.setGeometry(QtCore.QRect(240, 60, 54, 12))
        self.level1Lable.setObjectName("level1Lable")
        self.level2Lable = QtWidgets.QLabel(self.groupBox_3)
        self.level2Lable.setGeometry(QtCore.QRect(240, 100, 54, 12))
        self.level2Lable.setObjectName("level2Lable")
        self.level3Lable = QtWidgets.QLabel(self.groupBox_3)
        self.level3Lable.setGeometry(QtCore.QRect(240, 140, 54, 12))
        self.level3Lable.setObjectName("level3Lable")
        self.level4Lable = QtWidgets.QLabel(self.groupBox_3)
        self.level4Lable.setGeometry(QtCore.QRect(240, 180, 54, 12))
        self.level4Lable.setObjectName("level4Lable")
        self.borderLable = QtWidgets.QLabel(self.groupBox_3)
        self.borderLable.setGeometry(QtCore.QRect(300, 20, 31, 16))
        self.borderLable.setObjectName("borderLable")
        self.fontLable = QtWidgets.QLabel(self.groupBox_3)
        self.fontLable.setGeometry(QtCore.QRect(350, 20, 31, 16))
        self.fontLable.setObjectName("fontLable")
        self.heightLable = QtWidgets.QLabel(self.groupBox_3)
        self.heightLable.setGeometry(QtCore.QRect(400, 20, 31, 16))
        self.heightLable.setObjectName("heightLable")
        self.level1Width = QtWidgets.QSpinBox(self.groupBox_3)
        self.level1Width.setGeometry(QtCore.QRect(390, 50, 42, 22))
        self.level1Width.setMinimum(1)
        self.level1Width.setProperty("value", 3)
        self.level1Width.setObjectName("level1Width")
        self.level2Width = QtWidgets.QSpinBox(self.groupBox_3)
        self.level2Width.setGeometry(QtCore.QRect(390, 90, 42, 22))
        self.level2Width.setMinimum(1)
        self.level2Width.setProperty("value", 3)
        self.level2Width.setObjectName("level2Width")
        self.level3Width = QtWidgets.QSpinBox(self.groupBox_3)
        self.level3Width.setGeometry(QtCore.QRect(390, 130, 42, 22))
        self.level3Width.setMinimum(1)
        self.level3Width.setProperty("value", 3)
        self.level3Width.setObjectName("level3Width")
        self.level4Width = QtWidgets.QSpinBox(self.groupBox_3)
        self.level4Width.setGeometry(QtCore.QRect(390, 170, 42, 22))
        self.level4Width.setMinimum(1)
        self.level4Width.setProperty("value", 3)
        self.level4Width.setObjectName("level4Width")
        self.level1Border = QtWidgets.QPushButton(self.groupBox_3)
        self.level1Border.setGeometry(QtCore.QRect(300, 50, 21, 20))
        self.level1Border.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.level1Border.setAutoFillBackground(False)
        self.level1Border.setStyleSheet("background-color:rgb(0, 128, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"gridline-color:rgb(0, 0, 0);")
        self.level1Border.setText("")
        self.level1Border.setObjectName("level1Border")
        self.level2Border = QtWidgets.QPushButton(self.groupBox_3)
        self.level2Border.setGeometry(QtCore.QRect(300, 90, 21, 20))
        self.level2Border.setStyleSheet("background-color:rgb(128,0, 0);\n"
"border-color: rgb(0,0, 0);\n"
"gridline-color:rgb(0, 0, 0);")
        self.level2Border.setText("")
        self.level2Border.setObjectName("level2Border")
        self.level3Border = QtWidgets.QPushButton(self.groupBox_3)
        self.level3Border.setGeometry(QtCore.QRect(300, 130, 21, 20))
        self.level3Border.setStyleSheet("background-color:rgb(0, 0, 128);\n"
"border-color: rgb(0, 0, 0);\n"
"gridline-color:rgb(0, 0, 0);")
        self.level3Border.setText("")
        self.level3Border.setObjectName("level3Border")
        self.level4Border = QtWidgets.QPushButton(self.groupBox_3)
        self.level4Border.setGeometry(QtCore.QRect(300, 170, 21, 20))
        self.level4Border.setStyleSheet("background-color:rgb(255, 255, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"gridline-color:rgb(0, 0, 0);")
        self.level4Border.setText("")
        self.level4Border.setObjectName("level4Border")
        self.level1Font = QtWidgets.QPushButton(self.groupBox_3)
        self.level1Font.setGeometry(QtCore.QRect(350, 50, 21, 20))
        self.level1Font.setStyleSheet("background-color:rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"gridline-color:rgb(0, 0, 0);")
        self.level1Font.setText("")
        self.level1Font.setObjectName("level1Font")
        self.level2Font = QtWidgets.QPushButton(self.groupBox_3)
        self.level2Font.setGeometry(QtCore.QRect(350, 90, 21, 20))
        self.level2Font.setStyleSheet("background-color:rgb(0,0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"gridline-color:rgb(0, 0, 0);")
        self.level2Font.setText("")
        self.level2Font.setObjectName("level2Font")
        self.level3Font = QtWidgets.QPushButton(self.groupBox_3)
        self.level3Font.setGeometry(QtCore.QRect(350, 130, 21, 20))
        self.level3Font.setStyleSheet("background-color:rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"gridline-color:rgb(0, 0, 0);")
        self.level3Font.setText("")
        self.level3Font.setObjectName("level3Font")
        self.level4Font = QtWidgets.QPushButton(self.groupBox_3)
        self.level4Font.setGeometry(QtCore.QRect(350, 170, 21, 20))
        self.level4Font.setStyleSheet("background-color:rgb(0,0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"gridline-color:rgb(0, 0, 0);")
        self.level4Font.setText("")
        self.level4Font.setObjectName("level4Font")
        self.previewPic = QtWidgets.QListWidget(self.groupBox_3)
        self.previewPic.setGeometry(QtCore.QRect(10, 40, 211, 221))
        self.previewPic.setObjectName("previewPic")
        self.tabWidget.addTab(self.companyTab, "")
        self.departmentTab = QtWidgets.QWidget()
        self.departmentTab.setObjectName("departmentTab")
        self.groupBox_4 = QtWidgets.QGroupBox(self.departmentTab)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 20, 241, 621))
        self.groupBox_4.setObjectName("groupBox_4")
        self.departmentList = QtWidgets.QListWidget(self.groupBox_4)
        self.departmentList.setGeometry(QtCore.QRect(10, 20, 221, 561))
        self.departmentList.setObjectName("departmentList")
        self.AddDep = QtWidgets.QPushButton(self.groupBox_4)
        self.AddDep.setGeometry(QtCore.QRect(80, 590, 75, 23))
        self.AddDep.setObjectName("AddDep")
        self.DeleteDep = QtWidgets.QPushButton(self.groupBox_4)
        self.DeleteDep.setGeometry(QtCore.QRect(160, 590, 75, 23))
        self.DeleteDep.setObjectName("DeleteDep")
        self.groupBox_5 = QtWidgets.QGroupBox(self.departmentTab)
        self.groupBox_5.setGeometry(QtCore.QRect(290, 20, 661, 621))
        self.groupBox_5.setObjectName("groupBox_5")
        self.depIntro = QtWidgets.QPlainTextEdit(self.groupBox_5)
        self.depIntro.setGeometry(QtCore.QRect(20, 80, 631, 251))
        self.depIntro.setObjectName("depIntro")
        self.label_27 = QtWidgets.QLabel(self.groupBox_5)
        self.label_27.setGeometry(QtCore.QRect(20, 60, 54, 12))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_5)
        self.label_28.setGeometry(QtCore.QRect(20, 340, 54, 12))
        self.label_28.setObjectName("label_28")
        self.duty_1 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_1.setGeometry(QtCore.QRect(20, 360, 121, 16))
        self.duty_1.setChecked(False)
        self.duty_1.setObjectName("duty_1")
        self.duty_2 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_2.setGeometry(QtCore.QRect(20, 380, 91, 16))
        self.duty_2.setObjectName("duty_2")
        self.duty_3 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_3.setGeometry(QtCore.QRect(20, 400, 111, 16))
        self.duty_3.setObjectName("duty_3")
        self.duty_4 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_4.setGeometry(QtCore.QRect(20, 420, 131, 31))
        self.duty_4.setObjectName("duty_4")
        self.duty_5 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_5.setGeometry(QtCore.QRect(20, 450, 111, 31))
        self.duty_5.setObjectName("duty_5")
        self.duty_8 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_8.setGeometry(QtCore.QRect(20, 560, 101, 16))
        self.duty_8.setObjectName("duty_8")
        self.duty_7 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_7.setGeometry(QtCore.QRect(20, 520, 121, 31))
        self.duty_7.setObjectName("duty_7")
        self.duty_10 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_10.setGeometry(QtCore.QRect(150, 360, 111, 16))
        self.duty_10.setObjectName("duty_10")
        self.duty_13 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_13.setGeometry(QtCore.QRect(150, 420, 101, 16))
        self.duty_13.setObjectName("duty_13")
        self.duty_12 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_12.setGeometry(QtCore.QRect(150, 400, 91, 16))
        self.duty_12.setObjectName("duty_12")
        self.duty_11 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_11.setGeometry(QtCore.QRect(150, 380, 111, 16))
        self.duty_11.setObjectName("duty_11")
        self.duty_6 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_6.setGeometry(QtCore.QRect(20, 490, 121, 31))
        self.duty_6.setObjectName("duty_6")
        self.duty_16 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_16.setGeometry(QtCore.QRect(150, 520, 111, 16))
        self.duty_16.setObjectName("duty_16")
        self.duty_20 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_20.setGeometry(QtCore.QRect(280, 390, 111, 16))
        self.duty_20.setObjectName("duty_20")
        self.duty_19 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_19.setGeometry(QtCore.QRect(280, 350, 111, 41))
        self.duty_19.setObjectName("duty_19")
        self.duty_17 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_17.setGeometry(QtCore.QRect(150, 540, 101, 16))
        self.duty_17.setObjectName("duty_17")
        self.duty_18 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_18.setGeometry(QtCore.QRect(150, 560, 111, 41))
        self.duty_18.setObjectName("duty_18")
        self.duty_15 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_15.setGeometry(QtCore.QRect(150, 470, 111, 41))
        self.duty_15.setObjectName("duty_15")
        self.duty_21 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_21.setGeometry(QtCore.QRect(280, 410, 121, 31))
        self.duty_21.setObjectName("duty_21")
        self.duty_25 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_25.setGeometry(QtCore.QRect(280, 530, 121, 16))
        self.duty_25.setObjectName("duty_25")
        self.duty_24 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_24.setGeometry(QtCore.QRect(280, 510, 111, 16))
        self.duty_24.setObjectName("duty_24")
        self.duty_22 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_22.setGeometry(QtCore.QRect(280, 450, 121, 16))
        self.duty_22.setObjectName("duty_22")
        self.duty_23 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_23.setGeometry(QtCore.QRect(280, 470, 121, 41))
        self.duty_23.setObjectName("duty_23")
        self.duty_9 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_9.setGeometry(QtCore.QRect(20, 580, 121, 31))
        self.duty_9.setObjectName("duty_9")
        self.duty_26 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_26.setGeometry(QtCore.QRect(280, 550, 111, 16))
        self.duty_26.setObjectName("duty_26")
        self.duty_41 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_41.setGeometry(QtCore.QRect(540, 510, 101, 16))
        self.duty_41.setObjectName("duty_41")
        self.duty_29 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_29.setGeometry(QtCore.QRect(410, 380, 121, 31))
        self.duty_29.setObjectName("duty_29")
        self.duty_27 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_27.setGeometry(QtCore.QRect(280, 570, 131, 31))
        self.duty_27.setObjectName("duty_27")
        self.duty_28 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_28.setGeometry(QtCore.QRect(410, 350, 121, 31))
        self.duty_28.setObjectName("duty_28")
        self.duty_14 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_14.setGeometry(QtCore.QRect(150, 450, 121, 16))
        self.duty_14.setObjectName("duty_14")
        self.duty_31 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_31.setGeometry(QtCore.QRect(410, 440, 121, 31))
        self.duty_31.setObjectName("duty_31")
        self.duty_42 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_42.setGeometry(QtCore.QRect(540, 530, 121, 31))
        self.duty_42.setObjectName("duty_42")
        self.duty_34 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_34.setGeometry(QtCore.QRect(410, 540, 101, 16))
        self.duty_34.setObjectName("duty_34")
        self.duty_32 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_32.setGeometry(QtCore.QRect(410, 470, 121, 31))
        self.duty_32.setObjectName("duty_32")
        self.duty_33 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_33.setGeometry(QtCore.QRect(410, 500, 121, 31))
        self.duty_33.setObjectName("duty_33")
        self.duty_30 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_30.setGeometry(QtCore.QRect(410, 420, 121, 16))
        self.duty_30.setObjectName("duty_30")
        self.duty_35 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_35.setGeometry(QtCore.QRect(410, 560, 91, 16))
        self.duty_35.setObjectName("duty_35")
        self.duty_40 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_40.setGeometry(QtCore.QRect(540, 480, 101, 16))
        self.duty_40.setObjectName("duty_40")
        self.duty_39 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_39.setGeometry(QtCore.QRect(540, 450, 91, 16))
        self.duty_39.setObjectName("duty_39")
        self.duty_36 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_36.setGeometry(QtCore.QRect(540, 360, 91, 16))
        self.duty_36.setObjectName("duty_36")
        self.duty_37 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_37.setGeometry(QtCore.QRect(540, 390, 111, 16))
        self.duty_37.setObjectName("duty_37")
        self.duty_38 = QtWidgets.QCheckBox(self.groupBox_5)
        self.duty_38.setGeometry(QtCore.QRect(540, 410, 121, 31))
        self.duty_38.setObjectName("duty_38")
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setGeometry(QtCore.QRect(220, 30, 54, 12))
        self.label.setObjectName("label")
        self.depLevel = QtWidgets.QSpinBox(self.groupBox_5)
        self.depLevel.setGeometry(QtCore.QRect(280, 20, 42, 22))
        self.depLevel.setObjectName("depLevel")
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 54, 12))
        self.label_2.setObjectName("label_2")
        self.depName = QtWidgets.QLineEdit(self.groupBox_5)
        self.depName.setGeometry(QtCore.QRect(80, 20, 113, 20))
        self.depName.setObjectName("depName")
        self.addOrModifyDep = QtWidgets.QPushButton(self.groupBox_5)
        self.addOrModifyDep.setGeometry(QtCore.QRect(480, 590, 75, 23))
        self.addOrModifyDep.setObjectName("addOrModifyDep")
        self.cancelDep = QtWidgets.QPushButton(self.groupBox_5)
        self.cancelDep.setGeometry(QtCore.QRect(570, 590, 75, 23))
        self.cancelDep.setObjectName("cancelDep")
        self.tabWidget.addTab(self.departmentTab, "")
        self.createBotton = QtWidgets.QPushButton(self.centralwidget)
        self.createBotton.setGeometry(QtCore.QRect(830, 20, 75, 23))
        self.createBotton.setObjectName("createBotton")
        self.cancelButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelButton.setGeometry(QtCore.QRect(920, 20, 75, 23))
        self.cancelButton.setObjectName("cancelButton")
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(740, 20, 75, 23))
        self.searchButton.setObjectName("searchButton")
        self.searchContent = QtWidgets.QLineEdit(self.centralwidget)
        self.searchContent.setGeometry(QtCore.QRect(390, 20, 341, 20))
        self.searchContent.setObjectName("searchContent")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1013, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.basicInfo.setTitle(_translate("MainWindow", "基础信息"))
        self.coverFieldLable.setText(_translate("MainWindow", "业务范围"))
        self.fileNameLable.setText(_translate("MainWindow", "公司缩写"))
        self.companyLable.setText(_translate("MainWindow", "公司名"))
        self.addressLable.setText(_translate("MainWindow", "地址"))
        self.introductionLable.setText(_translate("MainWindow", "公司简介"))
        self.policyLable.setText(_translate("MainWindow", "服务方针"))
        self.fileInfo.setTitle(_translate("MainWindow", "文档信息"))
        self.auditDateText.setDisplayFormat(_translate("MainWindow", "yyyy年MM月dd日"))
        self.releaseDateText.setDisplayFormat(_translate("MainWindow", "yyyy年MM月dd日"))
        self.managerLable.setText(_translate("MainWindow", "总经理"))
        self.guandaiLable.setText(_translate("MainWindow", "管理者代表"))
        self.employeesLable.setText(_translate("MainWindow", "编制人"))
        self.approverLable.setText(_translate("MainWindow", "批准人"))
        self.auditLable.setText(_translate("MainWindow", "审计人"))
        self.announcerLable.setText(_translate("MainWindow", "发布人"))
        self.zipLable.setText(_translate("MainWindow", "邮编"))
        self.phoneLable.setText(_translate("MainWindow", "电话"))
        self.releaseDateLable.setText(_translate("MainWindow", "发布批准日期"))
        self.auditDateLable.setText(_translate("MainWindow", "审计日期"))
        self.groupBox_3.setTitle(_translate("MainWindow", "结构图"))
        self.depStructLable.setText(_translate("MainWindow", "部门结构"))
        self.previewButton.setText(_translate("MainWindow", "预览图片"))
        self.deSytle.setText(_translate("MainWindow", "样式"))
        self.level1Lable.setText(_translate("MainWindow", "第一层"))
        self.level2Lable.setText(_translate("MainWindow", "第二层"))
        self.level3Lable.setText(_translate("MainWindow", "第三层"))
        self.level4Lable.setText(_translate("MainWindow", "第四层"))
        self.borderLable.setText(_translate("MainWindow", "边框"))
        self.fontLable.setText(_translate("MainWindow", "字体"))
        self.heightLable.setText(_translate("MainWindow", "行宽"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.companyTab), _translate("MainWindow", "公司信息"))
        self.groupBox_4.setTitle(_translate("MainWindow", "部门列表"))
        self.AddDep.setText(_translate("MainWindow", "添加"))
        self.DeleteDep.setText(_translate("MainWindow", "删除"))
        self.groupBox_5.setTitle(_translate("MainWindow", "部门信息"))
        self.label_27.setText(_translate("MainWindow", "部门简介"))
        self.label_28.setText(_translate("MainWindow", "部门职责"))
        self.duty_1.setText(_translate("MainWindow", "4 管理体系要求"))
        self.duty_2.setText(_translate("MainWindow", "4.1 管理职责"))
        self.duty_3.setText(_translate("MainWindow", "4.1.1 管理承诺"))
        self.duty_4.setText(_translate("MainWindow", "4.1.2 服务管理方\n"
"针"))
        self.duty_5.setText(_translate("MainWindow", "4.1.3 权限、职\n"
"责和沟通"))
        self.duty_8.setText(_translate("MainWindow", "4.3 文件管理"))
        self.duty_7.setText(_translate("MainWindow", "4.2 治理由其他方\n"
"运行的过程"))
        self.duty_10.setText(_translate("MainWindow", "4.3.2 文件控制"))
        self.duty_13.setText(_translate("MainWindow", "4.4.1 资源提供"))
        self.duty_12.setText(_translate("MainWindow", "4.4 资源管理"))
        self.duty_11.setText(_translate("MainWindow", "4.3.3 记录控制"))
        self.duty_6.setText(_translate("MainWindow", "4.1.4 管理者代\n"
"表"))
        self.duty_16.setText(_translate("MainWindow", "4.5.1 定义范围"))
        self.duty_20.setText(_translate("MainWindow", "4.5.4.1 总要求"))
        self.duty_19.setText(_translate("MainWindow", "4.5.4 监视和评\n"
"审服务管理体系\n"
"（Check）"))
        self.duty_17.setText(_translate("MainWindow", "4.5.2 策划服务管理体系（Plan）"))
        self.duty_18.setText(_translate("MainWindow", "4.5.3 实施和运\n"
"行服务管理体系\n"
"（Do）"))
        self.duty_15.setText(_translate("MainWindow", "4.5 建立和改进\n"
"服务管理体系\n"
"（SMS）"))
        self.duty_21.setText(_translate("MainWindow", "4.5.4.2 内部审\n"
"核"))
        self.duty_25.setText(_translate("MainWindow", "4.5.5.2 管理改进"))
        self.duty_24.setText(_translate("MainWindow", "4.5.5.1 总要求"))
        self.duty_22.setText(_translate("MainWindow", "4.5.4.3 管理评审"))
        self.duty_23.setText(_translate("MainWindow", "4.5.5 维护和改进\n"
"服务管理体系\n"
"（Act）"))
        self.duty_9.setText(_translate("MainWindow", "4.3.1 文件的建立\n"
"和维护"))
        self.duty_26.setText(_translate("MainWindow", "5.1 总要求"))
        self.duty_41.setText(_translate("MainWindow", "9.2 变更管理"))
        self.duty_29.setText(_translate("MainWindow", "5.4 新的或变更的\n"
"服务转换"))
        self.duty_27.setText(_translate("MainWindow", "5.2 策划新的或变\n"
"更的服务"))
        self.duty_28.setText(_translate("MainWindow", "5.3 设计和开发新\n"
"的或变更的服务"))
        self.duty_14.setText(_translate("MainWindow", "4.4.2 人力资源"))
        self.duty_31.setText(_translate("MainWindow", "6.2 服务报告管\n"
"理"))
        self.duty_42.setText(_translate("MainWindow", "9.3 发布和部署管\n"
"理"))
        self.duty_34.setText(_translate("MainWindow", "6.5 能力管理"))
        self.duty_32.setText(_translate("MainWindow", "6.3 服务的连续性\n"
"可用性管理"))
        self.duty_33.setText(_translate("MainWindow", "6.4 服务的预算和\n"
"核算"))
        self.duty_30.setText(_translate("MainWindow", "6.1 服务级别管理"))
        self.duty_35.setText(_translate("MainWindow", "6.6 信息安全"))
        self.duty_40.setText(_translate("MainWindow", "9.1 配置管理"))
        self.duty_39.setText(_translate("MainWindow", "8.2 问题管理"))
        self.duty_36.setText(_translate("MainWindow", "7.1 业务关系管理"))
        self.duty_37.setText(_translate("MainWindow", "7.2 供应商管理"))
        self.duty_38.setText(_translate("MainWindow", "8.1 事件和服务请\n"
"求管理"))
        self.label.setText(_translate("MainWindow", "部门级别"))
        self.label_2.setText(_translate("MainWindow", "部门名称"))
        self.addOrModifyDep.setText(_translate("MainWindow", "保存修改"))
        self.cancelDep.setText(_translate("MainWindow", "放弃修改"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.departmentTab), _translate("MainWindow", "部门信息"))
        self.createBotton.setText(_translate("MainWindow", "文档生成"))
        self.cancelButton.setText(_translate("MainWindow", "取消"))
        self.searchButton.setText(_translate("MainWindow", "搜索"))

